var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var d=c++;return{value:b(d,a[d]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,c){return c})}},"es6","es3");
var ipconfignames={addr:"IP Address",subnet:"Subnet Mask",gateway:"Gateway Address",hostname:"Host Name",domainname:"Domain name",dns1:"DNS Server #1",dns2:"DNS Server #2"},dhcpoptions=["Disabled","Enabled"],commoptions=["Auto","10 HDX","10 FDX","100 HDX","100 FDX"],settingsuccessrestart="Settings successfully saved! A restart is required for the changes to take effect.",settingsuccessrestartprofi="Settings successfully saved! A restart is required for the changes to take effect.\n\nNote: The pending IP configuration could still be overwritten externally from a controller after the restart.",
settingsuccess="Settings successfully saved!";function selected(a,b){return a==b?"selected=true":""}function loadIpConf(){$.getJSON(dev.jsonURL(apiNetworkConfigPath+"ipconf.json")).done(function(a){if(a.hasOwnProperty("dhcp")){var b=[{key:"dhcp",name:"DHCP",value:a.dhcp,list:dhcpoptions}];delete a.dhcp}else b=null;a={heading:"IP Configuration",identifier:"ipconf",selects:b,inputs:a,names:ipconfignames};$("#ipconf").html(tmpl("tmpl-conf",a))})}
function loadEthConf(){$.getJSON(dev.jsonURL(apiNetworkConfigPath+"ethconf.json")).done(function(a){if(a.comm1.error)document.getElementById("ethconf").style.display="none";else{var b=[];a.hasOwnProperty("comm2")?(b.push({key:"comm1",name:"Port 1",value:a.comm1,list:commoptions}),b.push({key:"comm2",name:"Port 2",value:a.comm2,list:commoptions})):b.push({key:"comm1",name:"Port config",value:a.comm1,list:commoptions});a={heading:"Ethernet Configuration",identifier:"ethconf",selects:b,inputs:[],names:{}};
$("#ethconf").html(tmpl("tmpl-conf",a))}})}
function buildNwTables(a){$(a).each(function(a,c){var b=[];a=0;$(c.values).each(function(c,d){b.push({key:d.name,name:d.name,value:d.value});d.hasOwnProperty("enumstrings")&&(b[a].list=d.enumstrings);d.hasOwnProperty("type")?b[a].type=d.type:b[a].type="text";a+=1});var d={heading:c.title,identifier:c.identifier,params:b};$("#nwconf").append(tmpl("tmpl-nw-conf",d));for(a in c.values)d=document.getElementsByName(c.values[a].name)[0],"checkbox"==d.type&&(d.setAttribute("class","chkboxinput"),0!=d.value&&
(d.checked=!0)),c.values[a].hasOwnProperty("min")&&c.values[a].hasOwnProperty("max")&&(d.setAttribute("min",c.values[a].min),d.setAttribute("max",c.values[a].max)),c.values[a].hasOwnProperty("maxlength")&&d.setAttribute("maxlength",c.values[a].maxlength)})}
function loadNwConf(){var a=0;$.getJSON(dev.jsonURL(apiNetworkConfigPath+"nwconf.json")).done(function(b){$("#nwconf").html("");$(b).each(function(c,e){$.getJSON(dev.jsonURL(apiNetworkConfigPath+"nwconf.json"),{get:e.identifier}).done(function(c){$.extend(e,{values:c});a++;a==b.length&&buildNwTables(b)})})})}
function buttonClickFunction(a){includeCsrf();"ethconf"==a?$.getJSON(dev.jsonURL(apiNetworkConfigPath+"ethconf.json"),$("#ethconf form").serialize()).done(function(a){a.result==abp.ERR_NO_ERROR?(loadEthConf(),alert(settingsuccess)):alert("Failed to set Ethernet Config. Error: "+abp.errorToString(a.result))}):"ipconf"==a?$.getJSON(dev.jsonURL(apiNetworkConfigPath+"ipconf.json"),$("#ipconf form").serialize()).done(function(a){a.result==abp.ERR_NO_ERROR?(loadIpConf(),$.getJSON(dev.jsonURL(apiModuleStatusPath+
"info.json"),function(a){137===a.networktype||157===a.networktype||173===a.networktype||174===a.networktype?alert(settingsuccessrestartprofi):alert(settingsuccessrestart)})):alert("Failed to set IP Config. Error: "+abp.errorToString(a.result))}):$.getJSON(dev.jsonURL(apiNetworkConfigPath+"nwconf.json"),"set="+a+"&"+$("#"+a).serialize()).done(function(a){a.result==abp.ERR_NO_ERROR?(loadNwConf(),a.hasOwnProperty("message")?alert(a.message.replace("\\n","\n")):alert(settingsuccess)):a.hasOwnProperty("message")?
alert(a.message.replace("\\n","\n")):alert("Failed to set Config. Error: "+abp.errorToString(a.result))})}loadIpConf();loadEthConf();loadNwConf();
