var $jscomp={scope:{},findInternal:function(k,x,q){k instanceof String&&(k=String(k));for(var y=k.length,u=0;u<y;u++){var H=k[u];if(x.call(q,H,u,k))return{i:u,v:H}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(k,x,q){if(q.get||q.set)throw new TypeError("ES3 does not support getters and setters.");k!=Array.prototype&&k!=Object.prototype&&(k[x]=q.value)};
$jscomp.getGlobal=function(k){return"undefined"!=typeof window&&window===k?k:"undefined"!=typeof global&&null!=global?global:k};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(k,x,q,y){if(x){q=$jscomp.global;k=k.split(".");for(y=0;y<k.length-1;y++){var u=k[y];u in q||(q[u]={});q=q[u]}k=k[k.length-1];y=q[k];x=x(y);x!=y&&null!=x&&$jscomp.defineProperty(q,k,{configurable:!0,writable:!0,value:x})}};
$jscomp.polyfill("Array.prototype.find",function(k){return k?k:function(k,q){return $jscomp.findInternal(this,k,q).v}},"es6-impl","es3");
var editor=function(){function k(a,f){return a.length>f?a.substring(0,f-3)+"...":a}function x(a){for(var f=[],d=0;d<a.length;d++)f[d]="0"+a[d].charCodeAt(0).toString(16).toUpperCase(),f[d]=f[d].substr(-2);return f}function q(a){a=a.constructor===Array?a[0]:a;14<a.toString().length&&(a=Number.parseFloat(a).toExponential(8));return a}function y(a,f){a.str=0===a.lines?f:a.str+("<br/>"+f);a.lines+=1}function u(a,f){if(null==a.numsubelements)return!1;var d;d=1<a.datatype.length?f:0;var e=(a.datatype[d]==
abp.OCTET||a.datatype[d]==abp.CHAR)&&1<a.numsubelements[f];return a.datatype[d]==abp.CHAR&&1<a.numelements||e}function H(a){var f,d,e=null;1<a.datatype.length?(f=abp.parseStruct(a.max,a.datatype,z,a.numsubelements),d=abp.parseStruct(a.min,a.datatype,z,a.numsubelements),null!=a["default"]&&(e=abp.parseStruct(a["default"],a.datatype,z,a.numsubelements))):(f=abp.parseArray(a.max,a.datatype[0],z,a.numsubelements[0]),d=abp.parseArray(a.min,a.datatype[0],z,a.numsubelements[0]),null!=a["default"]&&(e=abp.parseArray(a["default"],
a.datatype[0],z,a.numsubelements[0])));for(var c=[],b=0;b<a.numelements;b++){var m={};1<a.datatype.length?(m.datatype=a.datatype[b],m.descriptor=a.descriptor[b],m.numsubelements=a.numsubelements[b],m.min=d[b],m.max=f[b],m.elementname=null!=a.elementname?a.elementname[b]:null,m.isStringType=u(a,b),m["default"]=null!=a["default"]?e[b]:null):(m.datatype=a.datatype[0],m.descriptor=a.descriptor[0],m.numsubelements=a.numsubelements[0],m.elementname=null!=a.elementname?a.elementname[0]:null,m.isStringType=
u(a,0),m.isStringType?(m.min=d,m.max=f):(m.min=d[0],m.max=f[0]),m["default"]=null!=a["default"]&&null!=e?e[0]:null);c.push(m)}return c}function D(a,f,d){var e=$("<option/>");f&&e.attr("value",f);e.text(a);d&&e.attr("selected",!0);return e}function L(a,f,d){var e=!1,c;for(c in f)c==d&&(e=!0),a.append(D(f[c],c,c==d));e||a.append(D(c+" (no string available)",c,!0))}function N(a,f,d,e,c){var b=$("<select/>");e.append(b);b.on("change",function(){b.attr("class","adi-field-input-edit");$(".adi-field-input").attr("disabled",
"disabled");$(".adi-field-checkbox").attr("disabled","disabled");d.find("button").removeAttr("disabled")});b.on("keydown",function(a){13==a.which&&d.find("button").click();if(27==a.which||9==a.which)b.attr("class","adi-field-input"),$(".adi-field-input").removeAttr("disabled"),$(".adi-field-checkbox").removeAttr("disabled"),d.find("button").attr("disabled","disabled"),adi.isReadable(f)&&b.val(c)});var m=function(a){var b=0,d;for(d in a)if(b++,1<b)return!0;return!1};adi.enumStrings(a.instance,c).then(function(e){if(m(e))L(b,
e,c);else{b.append(D(e[c],c,!0));var k=$("<img/>"),r=D("Loading parameter strings...");b.empty();k.attr("src","img/indicator_tiny.gif");b.append(r);b.attr("readonly",!0);d.append(k);adi.enumStrings(a.instance).then(function(a){r.remove();k.remove();L(b,a,c)})}adi.isWritable(f)||b.removeAttr("readonly")}).then(null,function(a){alert("error "+a)});b.adiValue=function(){return parseInt(b.val(),10)};b.adiReadOnly=function(a){a?b.attr("readonly",!0):b.removeAttr("readonly")};return b}function G(a,f,d,
e,c){var b=$("<input/>");b.attr("type","text");b.attr("spellcheck","false");"string"==typeof c&&(a=c.match(/\0/),null!=a&&(c=c.substr(0,a.index)));b.on("keydown",function(a){adi.isWritable(f)&&(13==a.which&&d.find("button").click(),27==a.which||9==a.which?(b.attr("class","adi-field-input"),$(".adi-field-input").removeAttr("disabled"),$(".adi-field-checkbox").removeAttr("disabled"),d.find("button").attr("disabled","disabled"),adi.isReadable(f)?b.val(c):b.val("")):(b.attr("class","adi-field-input-edit"),
$(".adi-field-input").attr("disabled","disabled"),$(".adi-field-checkbox").attr("disabled","disabled"),d.find("button").removeAttr("disabled")))});adi.isReadable(f)&&b.attr("value",c);e.append(b);b.adiValue=function(){return b.val()};b.adiReadOnly=function(a){a?b.attr("readonly",!0):b.removeAttr("readonly")};return b}function O(a,f,d,e,c){var b=G(a,f,d,e,c);b.adiValue=function(){return parseInt(b.val())};return b}function M(a,f,d,e,c){var b=G(a,f,d,e,c);b.adiValue=function(){return parseInt(b.val())};
return b}function P(a,f,d,e,c){var b=G(a,f,d,e,c);b.adiValue=function(){return new Big(b.val())};return b}function Q(a,f,d,e,c){var b=G(a,f,d,e,c);b.adiValue=function(){return parseFloat(b.val())};return b}function R(a,f,d,e,c){var b=$("<input/>");b.attr("type","checkbox");b.on("change",function(){b.attr("class","adi-field-checkbox-edit");$(".adi-field-checkbox").attr("disabled","disabled");$(".adi-field-input").attr("disabled","disabled");d.find("button").removeAttr("disabled")});b.on("keydown",
function(a){13==a.which&&d.find("button").click();if(27==a.which||9==a.which)b.attr("class","adi-field-checkbox"),$(".adi-field-checkbox").removeAttr("disabled"),$(".adi-field-input").removeAttr("disabled"),d.find("button").attr("disabled","disabled"),adi.isReadable(f)&&c?b.prop("checked",!0):b.prop("checked",!1)});adi.isReadable(f)&&c&&b.attr("checked","checked");e.append(b);b.adiValue=function(){return b.prop("checked")};b.adiReadOnly=function(a){a?b.attr("disabled",!0):b.removeAttr("disabled")};
return b}function K(a){var f=$("<div/>");f.text(a);f.adiValue=function(){return null};f.adiReadOnly=function(a){};return f}function S(a,f,d,e){var c=$("<button/>");c.addClass("adi-setbtn");c.text("Set");c.attr("disabled","disabled");c.on("click",function(){var b=f.adiValue(),c;c=H(a);var k;if(c[e].datatype!=abp.CHAR||1<a.datatype.length)k=e;if(c[e].datatype==abp.CHAR){var q=b.split("");c=abp.encodeArray(q,c[e].datatype,z)}else if(u(a,e)){for(var q=b.split(" "),r=0;r<q.length;r++)q[r]=parseInt(q[r],
16);c=abp.encodeArray(q,c[e].datatype,z)}else if(c[e].datatype==abp.FLOAT&&c[e].datatype==abp.DOUBLE||!isNaN(b))c=abp.encodeValue(b,c[e].datatype,z);else{alert('Failed to encode value "'+b+'". Please verify that it is formatted correctly.');return}null==c?alert('Failed to encode value "'+b+'". Please verify that it is formatted correctly.'):adi.setValue(a,c,k).then(function(b){d.find("button").attr("disabled","disabled");0!=b&&alert("Error ("+abp.errorToString(b)+") updating parameter "+a.instance)},
function(a){alert(a)})});return c}function A(a){return"object"==typeof a&&"error"in a}function T(a){var f="Fatal processing error(s): ";A(a.instance)&&(f+="No instance available ("+abp.errorToString(a.instance.error)+") ");A(a.datatype[0])&&(f+="No datatype available ("+abp.errorToString(a.datatype[0].error)+") ");A(a.numelements)&&(f+="No array size available ("+abp.errorToString(a.numelements.error)+") ");A(a.descriptor[0])&&(f+="No descriptor field available ("+abp.errorToString(a.descriptor[0].error)+
") ");return f}var z,B,J;return{init:function(a,f,d){J=a;B=f;z=d==abp.FORMAT_LE},paginate:function(a,f){0>a&&(a=0);a>=B&&(a=B-a%f);a+f>=B&&(f=Math.max(B-a,0));return adi.fetch(a,f).then(function(d){J.empty();for(var e=0;e<d.length;e++){var c=$("<tr/>");c.attr("class",e%2?"row-1":"row-2");var b=$("<td/>"),m=$("<td/>"),u=$("<td/>"),E=$('<td colspan="2"/>');b.text(d[e].instance);null==d[e].name&&(d[e].name="Parameter #"+d[e].instance);m.text(d[e].name);m.addClass("name-col");b.addClass("order-col");
var r=d[e];if(A(r.instance)||A(r.datatype[0])||A(r.numelements)||A(r.descriptor[0]))E.text(T(d[e]));else{var r=e,g=d[e];if(null==g.numsubelements){g.numsubelements=[];for(var p=0;p<g.datatype.length;p++)g.numsubelements[p]=1}if(null==g.min){for(var l=Array(g.datatype.length),p=0;p<g.datatype.length;p++){l[p]=Array(g.numsubelements[p]);for(var t=0;t<g.numsubelements[p];t++)l[p][t]=abp.getTypeMin(g.datatype[p])}g.min=abp.encodeStruct(l,g.datatype,z)}if(null==g.max){l=Array(g.datatype.length);for(p=
0;p<g.datatype.length;p++)for(l[p]=Array(g.numsubelements[p]),t=0;t<g.numsubelements[p];t++)l[p][t]=abp.getTypeMax(g.datatype[p]);g.max=abp.encodeStruct(l,g.datatype,z)}d[r]=g;1<d[e].datatype.length&&null!=d[e].elementname&&(c.append(b),c.append(m),c.append(u),c.append(E),J.append(c),c=$("<tr/>"),c.attr("class",e%2?"row-1":"row-2"),b=$("<td/>"),m=$("<td/>"),u=$("<td/>"),E=$('<td colspan="2"/>'),b.addClass("order-col"),m.addClass("name-col"));g=d[e];p=g.numelements;r=1<g.datatype.length?A(g.rawvalue)?
Array(g.datatype.length):abp.parseStruct(g.rawvalue,g.datatype,z,g.numsubelements):A(g.rawvalue)?Array(g.numelements):abp.parseArray(g.rawvalue,g.datatype[0],z,g.numsubelements[0]);l=H(g);g.datatype[0]==abp.CHAR&&1==g.datatype.length&&(p=1);for(var t=Array(p),h=0;h<p;h++){var v="inst"+g.instance+"_"+h,n;l[h].isStringType?(n=" ",l[h].datatype==abp.CHAR&&(n=""),n=1<g.datatype.length?r[h].join(n):r.join(n)):n=l[h].datatype==abp.BOOL||l[h].datatype==abp.BOOL1?1<g.datatype.length?r[h][0]:r[h]:r?r[h]:0;
t[h]=$("<div/>").attr("id",v);var v=$("<div/>"),C=!0;1<l[h].numsubelements&&l[h].datatype!=abp.CHAR&&l[h].datatype!=abp.OCTET&&(C=!1);if(C){switch(l[h].datatype){case abp.BOOL:case abp.BOOL1:n=R(g,l[h].descriptor,t[h],v,n);break;case abp.ENUM:n=N(g,l[h].descriptor,t[h],v,n);break;case abp.UINT8:case abp.SINT8:case abp.UINT16:case abp.SINT16:case abp.UINT32:case abp.SINT32:n=O(g,l[h].descriptor,t[h],v,n);break;case abp.CHAR:n=G(g,l[h].descriptor,t[h],v,n);break;case abp.OCTET:n=l[h].isStringType?G(g,
l[h].descriptor,t[h],v,n):M(g,l[h].descriptor,t[h],v,n);break;case abp.BIT1:case abp.BIT2:case abp.BIT3:case abp.BIT4:case abp.BIT5:case abp.BIT6:case abp.BIT7:case abp.BITS8:case abp.BITS16:case abp.BITS32:n=M(g,l[h].descriptor,t[h],v,n);break;case abp.FLOAT:case abp.DOUBLE:n=Q(g,l[h].descriptor,t[h],v,n);break;case abp.UINT64:case abp.SINT64:n=P(g,l[h].descriptor,t[h],v,n);break;default:n=abp.isPadType(l[h].datatype)?K("Reserved"):K("Unknown"),v.append(n)}if(!abp.isPadType(l[h].datatype)){var B,
w=l[h],I=null,D=$("<span/>"),F={str:"",lines:0};D.attr("class","tooltiptext");switch(w.datatype){case abp.FLOAT:case abp.UINT64:case abp.SINT64:case abp.DOUBLE:B=q(w.min);C=q(w.max);null!=w["default"]&&(I=q(w["default"]));break;case abp.CHAR:B=x(w.min);C=x(w.max);null!=w["default"]&&(I=x(w["default"]));break;default:B=w.min,C=w.max,I=w["default"]}w.datatype!=abp.BOOL1&&w.datatype!=abp.BOOL&&w.datatype!=abp.BIT1&&(y(F,k("Min: "+B,21)),y(F,k("Max: "+C,21)));null!=I&&y(F,k("Default: "+I,21));adi.isNvsParameter(w.descriptor)&&
y(F,"Non-Volatile");0==F.lines?C=null:(D.html(F.str),D.attr("style","margin-top:-"+(7*F.lines-4).toString()+"px;"),C=D);null!=C&&(v.addClass("tooltip"),v.append(C))}}else n=K("Unsupported"),v.append(n);t[h].append(v);adi.isWritable(l[h].descriptor)&&!abp.isPadType(l[h].datatype)&&(v=getBase64EncodedCookie("role"),null!==v&&"administrator"!==v&&"operator"!==v||t[h].append(S(g,n,t[h],h)));n.adiReadOnly(!adi.isWritable(l[h].descriptor));l[h].datatype==abp.BOOL||l[h].datatype==abp.BOOL1?n.addClass("adi-field-checkbox"):
abp.isPadType(l[h].datatype)?n.addClass("adi-field-text"):n.addClass("adi-field-input")}r=t;for(g=0;g<r.length;g++)d[e].datatype[g]!=abp.PAD0&&(u.attr("class","right"),null!=d[e].elementname&&(m.html(d[e].elementname[g]),""!=d[e].elementname[g]&&1<r.length&&(p=e%2?"alt-1":"alt-2",m.addClass(p),u.addClass(p),E.addClass(p))),1<r.length&&u.append(g+":"),E.append(r[g]),b.addClass("order-col"),m.addClass("name-col"),c.append(b),c.append(m),c.append(u),c.append(E),J.append(c),c=$("<tr/>"),c.attr("class",
e%2?"row-1":"row-2"),b=$("<td/>"),m=$("<td/>"),u=$("<td/>"),E=$('<td colspan="2"/>'))}}return{offset:a,count:f}})}}}();
