/*
 jQuery JavaScript Library v3.6.0
 https://jquery.com/

 Includes Sizzle.js
 https://sizzlejs.com/

 Copyright OpenJS Foundation and other contributors
 Released under the MIT license
 https://jquery.org/license

 Date: 2021-03-02T17:08Z
 Sizzle CSS Selector Engine v2.3.6
 https://sizzlejs.com/

 Copyright JS Foundation and other contributors
 Released under the MIT license
 https://js.foundation/

 Date: 2021-02-16
*/
var $jscomp={scope:{},findInternal:function(p,A,F){p instanceof String&&(p=String(p));for(var H=p.length,G=0;G<H;G++){var E=p[G];if(A.call(F,E,G,p))return{i:G,v:E}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(p,A,F){if(F.get||F.set)throw new TypeError("ES3 does not support getters and setters.");p!=Array.prototype&&p!=Object.prototype&&(p[A]=F.value)};
$jscomp.getGlobal=function(p){return"undefined"!=typeof window&&window===p?p:"undefined"!=typeof global&&null!=global?global:p};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(p,A,F,H){if(A){F=$jscomp.global;p=p.split(".");for(H=0;H<p.length-1;H++){var G=p[H];G in F||(F[G]={});F=F[G]}p=p[p.length-1];H=F[p];A=A(H);A!=H&&null!=A&&$jscomp.defineProperty(F,p,{configurable:!0,writable:!0,value:A})}};
$jscomp.polyfill("Array.prototype.find",function(p){return p?p:function(p,F){return $jscomp.findInternal(this,p,F).v}},"es6-impl","es3");
(function(p,A){"object"===typeof module&&"object"===typeof module.exports?module.exports=p.document?A(p,!0):function(p){if(!p.document)throw Error("jQuery requires a window with a document");return A(p)}:A(p)})("undefined"!==typeof window?window:this,function(p,A){function F(a,b,c){c=c||u;var e,d=c.createElement("script");d.text=a;if(b)for(e in Sb)(a=b[e]||b.getAttribute&&b.getAttribute(e))&&d.setAttribute(e,a);c.head.appendChild(d).parentNode.removeChild(d)}function H(a){return null==a?a+"":"object"===
typeof a||"function"===typeof a?ta[cb.call(a)]||"object":typeof a}function G(a){var b=!!a&&"length"in a&&a.length,c=H(a);return r(a)||ka(a)?!1:"array"===c||0===b||"number"===typeof b&&0<b&&b-1 in a}function E(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()}function Na(a,b,c){return r(b)?d.grep(a,function(a,d){return!!b.call(a,d,a)!==c}):b.nodeType?d.grep(a,function(a){return a===b!==c}):"string"!==typeof b?d.grep(a,function(a){return-1<ua.call(b,a)!==c}):d.filter(b,a,c)}function db(a,
b){for(;(a=a[b])&&1!==a.nodeType;);return a}function Tb(a){var b={};d.each(a.match(R)||[],function(a,e){b[e]=!0});return b}function la(a){return a}function va(a){throw a;}function eb(a,b,c,e){var d;try{a&&r(d=a.promise)?d.call(a).done(b).fail(c):a&&r(d=a.then)?d.call(a,b,c):b.apply(void 0,[a].slice(e))}catch(g){c.apply(void 0,[g])}}function Da(){u.removeEventListener("DOMContentLoaded",Da);p.removeEventListener("load",Da);d.ready()}function Ub(a,b){return b.toUpperCase()}function Q(a){return a.replace(Vb,
"ms-").replace(Wb,Ub)}function wa(){this.expando=d.expando+wa.uid++}function fb(a,b,c){if(void 0===c&&1===a.nodeType)if(c="data-"+b.replace(Xb,"-$&").toLowerCase(),c=a.getAttribute(c),"string"===typeof c){try{var e=c;c="true"===e?!0:"false"===e?!1:"null"===e?null:e===+e+""?+e:Yb.test(e)?JSON.parse(e):e}catch(f){}N.set(a,b,c)}else c=void 0;return c}function gb(a,b,c,e){var f,g,h=20,k=e?function(){return e.cur()}:function(){return d.css(a,b,"")},l=k(),n=c&&c[3]||(d.cssNumber[b]?"":"px"),q=a.nodeType&&
(d.cssNumber[b]||"px"!==n&&+l)&&ca.exec(d.css(a,b));if(q&&q[3]!==n){l/=2;n=n||q[3];for(q=+l||1;h--;)d.style(a,b,q+n),0>=(1-g)*(1-(g=k()/l||.5))&&(h=0),q/=g;q*=2;d.style(a,b,q+n);c=c||[]}c&&(q=+q||+l||0,f=c[1]?q+(c[1]+1)*c[2]:+c[2],e&&(e.unit=n,e.start=q,e.end=f));return f}function ea(a,b){for(var c,e,f=[],g=0,h=a.length;g<h;g++)if(e=a[g],e.style)if(c=e.style.display,b){if("none"===c&&(f[g]=x.get(e,"display")||null,f[g]||(e.style.display="")),""===e.style.display&&Ga(e)){c=g;var k;k=e.ownerDocument;
e=e.nodeName;var l=hb[e];l||(k=k.body.appendChild(k.createElement(e)),l=d.css(k,"display"),k.parentNode.removeChild(k),"none"===l&&(l="block"),hb[e]=l);k=l;f[c]=k}}else"none"!==c&&(f[g]="none",x.set(e,"display",c));for(g=0;g<h;g++)null!=f[g]&&(a[g].style.display=f[g]);return a}function O(a,b){var c;c="undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName(b||"*"):"undefined"!==typeof a.querySelectorAll?a.querySelectorAll(b||"*"):[];return void 0===b||b&&E(a,b)?d.merge([a],c):c}function Oa(a,
b){for(var c=0,e=a.length;c<e;c++)x.set(a[c],"globalEval",!b||x.get(b[c],"globalEval"))}function ib(a,b,c,e,f){for(var g,h,k,l=b.createDocumentFragment(),n=[],q=0,I=a.length;q<I;q++)if((g=a[q])||0===g)if("object"===H(g))d.merge(n,g.nodeType?[g]:g);else if(Zb.test(g)){h=h||l.appendChild(b.createElement("div"));k=(jb.exec(g)||["",""])[1].toLowerCase();k=C[k]||C._default;h.innerHTML=k[1]+d.htmlPrefilter(g)+k[2];for(k=k[0];k--;)h=h.lastChild;d.merge(n,h.childNodes);h=l.firstChild;h.textContent=""}else n.push(b.createTextNode(g));
l.textContent="";for(q=0;g=n[q++];)if(e&&-1<d.inArray(g,e))f&&f.push(g);else if(a=ma(g),h=O(l.appendChild(g),"script"),a&&Oa(h),c)for(k=0;g=h[k++];)kb.test(g.type||"")&&c.push(g);return l}function W(){return!0}function na(){return!1}function $b(a,b){var c;a:{try{c=u.activeElement;break a}catch(e){}c=void 0}return a===c===("focus"===b)}function Pa(a,b,c,e,f,g){var h,k;if("object"===typeof b){"string"!==typeof c&&(e=e||c,c=void 0);for(k in b)Pa(a,k,c,e,b[k],g);return a}null==e&&null==f?(f=c,e=c=void 0):
null==f&&("string"===typeof c?(f=e,e=void 0):(f=e,e=c,c=void 0));if(!1===f)f=na;else if(!f)return a;1===g&&(h=f,f=function(a){d().off(a);return h.apply(this,arguments)},f.guid=h.guid||(h.guid=d.guid++));return a.each(function(){d.event.add(this,b,f,e,c)})}function Ha(a,b,c){c?(x.set(a,b,!1),d.event.add(a,b,{namespace:!1,handler:function(a){var e,g,h=x.get(this,b);if(a.isTrigger&1&&this[b])if(h.length)(d.event.special[b]||{}).delegateType&&a.stopPropagation();else{if(h=X.call(arguments),x.set(this,
b,h),e=c(this,b),this[b](),g=x.get(this,b),h!==g||e?x.set(this,b,!1):g={},h!==g)return a.stopImmediatePropagation(),a.preventDefault(),g&&g.value}else h.length&&(x.set(this,b,{value:d.event.trigger(d.extend(h[0],d.Event.prototype),h.slice(1),this)}),a.stopImmediatePropagation())}})):void 0===x.get(a,b)&&d.event.add(a,b,W)}function lb(a,b){return E(a,"table")&&E(11!==b.nodeType?b:b.firstChild,"tr")?d(a).children("tbody")[0]||a:a}function ac(a){a.type=(null!==a.getAttribute("type"))+"/"+a.type;return a}
function bc(a){"true/"===(a.type||"").slice(0,5)?a.type=a.type.slice(5):a.removeAttribute("type");return a}function mb(a,b){var c,e,f,g;if(1===b.nodeType){if(x.hasData(a)&&(c=x.get(a),g=c.events))for(f in x.remove(b,"handle events"),g)for(c=0,e=g[f].length;c<e;c++)d.event.add(b,f,g[f][c]);N.hasData(a)&&(f=N.access(a),f=d.extend({},f),N.set(b,f))}}function fa(a,b,c,e){b=nb(b);var f,g,h,k,l=0,n=a.length,q=n-1,I=b[0],m=r(I);if(m||1<n&&"string"===typeof I&&!v.checkClone&&cc.test(I))return a.each(function(d){var f=
a.eq(d);m&&(b[0]=I.call(this,d,f.html()));fa(f,b,c,e)});if(n&&(f=ib(b,a[0].ownerDocument,!1,a,e),g=f.firstChild,1===f.childNodes.length&&(f=g),g||e)){g=d.map(O(f,"script"),ac);for(h=g.length;l<n;l++)k=f,l!==q&&(k=d.clone(k,!0,!0),h&&d.merge(g,O(k,"script"))),c.call(a[l],k,l);if(h)for(f=g[g.length-1].ownerDocument,d.map(g,bc),l=0;l<h;l++)k=g[l],kb.test(k.type||"")&&!x.access(k,"globalEval")&&d.contains(f,k)&&(k.src&&"module"!==(k.type||"").toLowerCase()?d._evalUrl&&!k.noModule&&d._evalUrl(k.src,{nonce:k.nonce||
k.getAttribute("nonce")},f):F(k.textContent.replace(dc,""),k,f))}return a}function ob(a,b,c){for(var e=b?d.filter(b,a):a,f=0;null!=(b=e[f]);f++)c||1!==b.nodeType||d.cleanData(O(b)),b.parentNode&&(c&&ma(b)&&Oa(O(b,"script")),b.parentNode.removeChild(b));return a}function xa(a,b,c){var e,f,g=a.style;if(c=c||Ia(a))f=c.getPropertyValue(b)||c[b],""!==f||ma(a)||(f=d.style(a,b)),!v.pixelBoxStyles()&&Qa.test(f)&&ec.test(b)&&(a=g.width,b=g.minWidth,e=g.maxWidth,g.minWidth=g.maxWidth=g.width=f,f=c.width,g.width=
a,g.minWidth=b,g.maxWidth=e);return void 0!==f?f+"":f}function pb(a,b){return{get:function(){if(a())delete this.get;else return(this.get=b).apply(this,arguments)}}}function Ra(a){var b=d.cssProps[a]||qb[a];if(b)return b;if(a in rb)return a;a:{for(var b=a,c=b[0].toUpperCase()+b.slice(1),e=sb.length;e--;)if(b=sb[e]+c,b in rb)break a;b=void 0}return qb[a]=b||a}function tb(a,b,c){return(a=ca.exec(b))?Math.max(0,a[2]-(c||0))+(a[3]||"px"):b}function Sa(a,b,c,e,f,g){var h="width"===b?1:0,k=0,l=0;if(c===
(e?"border":"content"))return 0;for(;4>h;h+=2)"margin"===c&&(l+=d.css(a,c+J[h],!0,f)),e?("content"===c&&(l-=d.css(a,"padding"+J[h],!0,f)),"margin"!==c&&(l-=d.css(a,"border"+J[h]+"Width",!0,f))):(l+=d.css(a,"padding"+J[h],!0,f),"padding"!==c?l+=d.css(a,"border"+J[h]+"Width",!0,f):k+=d.css(a,"border"+J[h]+"Width",!0,f));!e&&0<=g&&(l+=Math.max(0,Math.ceil(a["offset"+b[0].toUpperCase()+b.slice(1)]-g-l-k-.5))||0);return l}function ub(a,b,c){var e=Ia(a),f=(!v.boxSizingReliable()||c)&&"border-box"===d.css(a,
"boxSizing",!1,e),g=f,h=xa(a,b,e),k="offset"+b[0].toUpperCase()+b.slice(1);if(Qa.test(h)){if(!c)return h;h="auto"}(!v.boxSizingReliable()&&f||!v.reliableTrDimensions()&&E(a,"tr")||"auto"===h||!parseFloat(h)&&"inline"===d.css(a,"display",!1,e))&&a.getClientRects().length&&(f="border-box"===d.css(a,"boxSizing",!1,e),(g=k in a)&&(h=a[k]));h=parseFloat(h)||0;return h+Sa(a,b,c||(f?"border":"content"),g,e,h)+"px"}function K(a,b,c,e,d){return new K.prototype.init(a,b,c,e,d)}function Ta(){Ja&&(!1===u.hidden&&
p.requestAnimationFrame?p.requestAnimationFrame(Ta):p.setTimeout(Ta,d.fx.interval),d.fx.tick())}function vb(){p.setTimeout(function(){oa=void 0});return oa=Date.now()}function Ka(a,b){var c,e=0,d={height:a};for(b=b?1:0;4>e;e+=2-b)c=J[e],d["margin"+c]=d["padding"+c]=a;b&&(d.opacity=d.width=a);return d}function wb(a,b,c){for(var e,d=(L.tweeners[b]||[]).concat(L.tweeners["*"]),g=0,h=d.length;g<h;g++)if(e=d[g].call(c,b,a))return e}function fc(a,b){var c,e,f,g,h;for(c in a)if(e=Q(c),f=b[e],g=a[c],Array.isArray(g)&&
(f=g[1],g=a[c]=g[0]),c!==e&&(a[e]=g,delete a[c]),(h=d.cssHooks[e])&&"expand"in h)for(c in g=h.expand(g),delete a[e],g)c in a||(a[c]=g[c],b[c]=f);else b[e]=f}function L(a,b,c){var e,f=0,g=L.prefilters.length,h=d.Deferred().always(function(){delete k.elem}),k=function(){if(e)return!1;for(var b=oa||vb(),b=Math.max(0,l.startTime+l.duration-b),c=1-(b/l.duration||0),d=0,f=l.tweens.length;d<f;d++)l.tweens[d].run(c);h.notifyWith(a,[l,c,b]);if(1>c&&f)return b;f||h.notifyWith(a,[l,1,0]);h.resolveWith(a,[l]);
return!1},l=h.promise({elem:a,props:d.extend({},b),opts:d.extend(!0,{specialEasing:{},easing:d.easing._default},c),originalProperties:b,originalOptions:c,startTime:oa||vb(),duration:c.duration,tweens:[],createTween:function(b,c){var e=d.Tween(a,l.opts,b,c,l.opts.specialEasing[b]||l.opts.easing);l.tweens.push(e);return e},stop:function(b){var c=0,d=b?l.tweens.length:0;if(e)return this;for(e=!0;c<d;c++)l.tweens[c].run(1);b?(h.notifyWith(a,[l,1,0]),h.resolveWith(a,[l,b])):h.rejectWith(a,[l,b]);return this}});
c=l.props;for(fc(c,l.opts.specialEasing);f<g;f++)if(b=L.prefilters[f].call(l,a,c,l.opts))return r(b.stop)&&(d._queueHooks(l.elem,l.opts.queue).stop=b.stop.bind(b)),b;d.map(c,wb,l);r(l.opts.start)&&l.opts.start.call(a,l);l.progress(l.opts.progress).done(l.opts.done,l.opts.complete).fail(l.opts.fail).always(l.opts.always);d.fx.timer(d.extend(k,{elem:a,anim:l,queue:l.opts.queue}));return l}function da(a){return(a.match(R)||[]).join(" ")}function T(a){return a.getAttribute&&a.getAttribute("class")||""}
function Ua(a){return Array.isArray(a)?a:"string"===typeof a?a.match(R)||[]:[]}function Va(a,b,c,e){var f;if(Array.isArray(b))d.each(b,function(b,d){c||gc.test(a)?e(a,d):Va(a+"["+("object"===typeof d&&null!=d?b:"")+"]",d,c,e)});else if(c||"object"!==H(b))e(a,b);else for(f in b)Va(a+"["+f+"]",b[f],c,e)}function xb(a){return function(b,c){"string"!==typeof b&&(c=b,b="*");var e,d=0,g=b.toLowerCase().match(R)||[];if(r(c))for(;e=g[d++];)"+"===e[0]?(e=e.slice(1)||"*",(a[e]=a[e]||[]).unshift(c)):(a[e]=a[e]||
[]).push(c)}}function yb(a,b,c,e){function f(k){var l;g[k]=!0;d.each(a[k]||[],function(a,d){var k=d(b,c,e);if("string"===typeof k&&!h&&!g[k])return b.dataTypes.unshift(k),f(k),!1;if(h)return!(l=k)});return l}var g={},h=a===Wa;return f(b.dataTypes[0])||!g["*"]&&f("*")}function Xa(a,b){var c,e,f=d.ajaxSettings.flatOptions||{};for(c in b)void 0!==b[c]&&((f[c]?a:e||(e={}))[c]=b[c]);e&&d.extend(!0,a,e);return a}function hc(a,b,c){for(var e,d,g,h,k=a.contents,l=a.dataTypes;"*"===l[0];)l.shift(),void 0===
e&&(e=a.mimeType||b.getResponseHeader("Content-Type"));if(e)for(d in k)if(k[d]&&k[d].test(e)){l.unshift(d);break}if(l[0]in c)g=l[0];else{for(d in c){if(!l[0]||a.converters[d+" "+l[0]]){g=d;break}h||(h=d)}g=g||h}if(g)return g!==l[0]&&l.unshift(g),c[g]}function ic(a,b,c,e){var d,g,h,k,l,n={},q=a.dataTypes.slice();if(q[1])for(h in a.converters)n[h.toLowerCase()]=a.converters[h];for(g=q.shift();g;)if(a.responseFields[g]&&(c[a.responseFields[g]]=b),!l&&e&&a.dataFilter&&(b=a.dataFilter(b,a.dataType)),l=
g,g=q.shift())if("*"===g)g=l;else if("*"!==l&&l!==g){h=n[l+" "+g]||n["* "+g];if(!h)for(d in n)if(k=d.split(" "),k[1]===g&&(h=n[l+" "+k[0]]||n["* "+k[0]])){!0===h?h=n[d]:!0!==n[d]&&(g=k[0],q.unshift(k[1]));break}if(!0!==h)if(h&&a["throws"])b=h(b);else try{b=h(b)}catch(I){return{state:"parsererror",error:h?I:"No conversion from "+l+" to "+g}}}return{state:"success",data:b}}var Y=[],zb=Object.getPrototypeOf,X=Y.slice,nb=Y.flat?function(a){return Y.flat.call(a)}:function(a){return Y.concat.apply([],a)},
Ya=Y.push,ua=Y.indexOf,ta={},cb=ta.toString,La=ta.hasOwnProperty,Ab=La.toString,jc=Ab.call(Object),v={},r=function(a){return"function"===typeof a&&"number"!==typeof a.nodeType&&"function"!==typeof a.item},ka=function(a){return null!=a&&a===a.window},u=p.document,Sb={type:!0,src:!0,nonce:!0,noModule:!0},d=function(a,b){return new d.fn.init(a,b)};d.fn=d.prototype={jquery:"3.6.0",constructor:d,length:0,toArray:function(){return X.call(this)},get:function(a){return null==a?X.call(this):0>a?this[a+this.length]:
this[a]},pushStack:function(a){a=d.merge(this.constructor(),a);a.prevObject=this;return a},each:function(a){return d.each(this,a)},map:function(a){return this.pushStack(d.map(this,function(b,c){return a.call(b,c,b)}))},slice:function(){return this.pushStack(X.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},even:function(){return this.pushStack(d.grep(this,function(a,b){return(b+1)%2}))},odd:function(){return this.pushStack(d.grep(this,function(a,b){return b%
2}))},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},end:function(){return this.prevObject||this.constructor()},push:Ya,sort:Y.sort,splice:Y.splice};d.extend=d.fn.extend=function(){var a,b,c,e,f,g=arguments[0]||{},h=1,k=arguments.length,l=!1;"boolean"===typeof g&&(l=g,g=arguments[h]||{},h++);"object"===typeof g||r(g)||(g={});h===k&&(g=this,h--);for(;h<k;h++)if(null!=(a=arguments[h]))for(b in a)e=a[b],"__proto__"!==b&&g!==e&&(l&&e&&(d.isPlainObject(e)||
(f=Array.isArray(e)))?(c=g[b],c=f&&!Array.isArray(c)?[]:f||d.isPlainObject(c)?c:{},f=!1,g[b]=d.extend(l,c,e)):void 0!==e&&(g[b]=e));return g};d.extend({expando:"jQuery"+("3.6.0"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},noop:function(){},isPlainObject:function(a){if(!a||"[object Object]"!==cb.call(a))return!1;a=zb(a);if(!a)return!0;a=La.call(a,"constructor")&&a.constructor;return"function"===typeof a&&Ab.call(a)===jc},isEmptyObject:function(a){for(var b in a)return!1;
return!0},globalEval:function(a,b,c){F(a,{nonce:b&&b.nonce},c)},each:function(a,b){var c,d=0;if(G(a))for(c=a.length;d<c&&!1!==b.call(a[d],d,a[d]);d++);else for(d in a)if(!1===b.call(a[d],d,a[d]))break;return a},makeArray:function(a,b){var c=b||[];null!=a&&(G(Object(a))?d.merge(c,"string"===typeof a?[a]:a):Ya.call(c,a));return c},inArray:function(a,b,c){return null==b?-1:ua.call(b,a,c)},merge:function(a,b){for(var c=+b.length,d=0,f=a.length;d<c;d++)a[f++]=b[d];a.length=f;return a},grep:function(a,
b,c){for(var d=[],f=0,g=a.length,h=!c;f<g;f++)c=!b(a[f],f),c!==h&&d.push(a[f]);return d},map:function(a,b,c){var d,f,g=0,h=[];if(G(a))for(d=a.length;g<d;g++)f=b(a[g],g,c),null!=f&&h.push(f);else for(g in a)f=b(a[g],g,c),null!=f&&h.push(f);return nb(h)},guid:1,support:v});"function"===typeof Symbol&&(d.fn[Symbol.iterator]=Y[Symbol.iterator]);d.each("Boolean Number String Function Array Date RegExp Object Error Symbol".split(" "),function(a,b){ta["[object "+b+"]"]=b.toLowerCase()});var aa=function(a){function b(a,
b,c,d){var e,f,g,t,h,z=b&&b.ownerDocument;f=b?b.nodeType:9;c=c||[];if("string"!==typeof a||!a||1!==f&&9!==f&&11!==f)return c;if(!d&&(C(b),b=b||B,U)){if(11!==f&&(h=Ca.exec(a)))if(e=h[1])if(9===f)if(g=b.getElementById(e)){if(g.id===e)return c.push(g),c}else return c;else{if(z&&(g=z.getElementById(e))&&Q(b,g)&&g.id===e)return c.push(g),c}else{if(h[2])return qa.apply(c,b.getElementsByTagName(a)),c;if((e=h[3])&&w.getElementsByClassName&&b.getElementsByClassName)return qa.apply(c,b.getElementsByClassName(e)),
c}if(!(!w.qsa||T[a+" "]||M&&M.test(a)||1===f&&"object"===b.nodeName.toLowerCase())){e=a;z=b;if(1===f&&(oa.test(a)||fa.test(a))){z=ja.test(a)&&I(b.parentNode)||b;z===b&&w.scope||((t=b.getAttribute("id"))?t=t.replace(ta,ua):b.setAttribute("id",t=D));e=E(a);for(f=e.length;f--;)e[f]=(t?"#"+t:":scope")+" "+p(e[f]);e=e.join(",")}try{return qa.apply(c,z.querySelectorAll(e)),c}catch(Jc){T(a,!0)}finally{t===D&&b.removeAttribute("id")}}}return O(a.replace(W,"$1"),b,c,d)}function c(){function a(c,d){b.push(c+
" ")>y.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function d(a){a[D]=!0;return a}function f(a){var b=B.createElement("fieldset");try{return!!a(b)}catch(z){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function g(a,b){for(var c=a.split("|"),d=c.length;d--;)y.attrHandle[c[d]]=b}function h(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&a.sourceIndex-b.sourceIndex;if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function k(a){return function(b){return"input"===
b.nodeName.toLowerCase()&&b.type===a}}function l(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function n(a){return function(b){return"form"in b?b.parentNode&&!1===b.disabled?"label"in b?"label"in b.parentNode?b.parentNode.disabled===a:b.disabled===a:b.isDisabled===a||b.isDisabled!==!a&&Da(b)===a:b.disabled===a:"label"in b?b.disabled===a:!1}}function q(a){return d(function(b){b=+b;return d(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=
f[g]]&&(c[e]=!(d[e]=c[e]))})})}function I(a){return a&&"undefined"!==typeof a.getElementsByTagName&&a}function m(){}function p(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function x(a,b,c){var d=b.dir,e=b.next,f=e||d,g=c&&"parentNode"===f,h=Y++;return b.first?function(b,c,e){for(;b=b[d];)if(1===b.nodeType||g)return a(b,c,e);return!1}:function(b,c,t){var k,z,l=[J,h];if(t)for(;b=b[d];){if((1===b.nodeType||g)&&a(b,c,t))return!0}else for(;b=b[d];)if(1===b.nodeType||g)if(z=b[D]||(b[D]=
{}),z=z[b.uniqueID]||(z[b.uniqueID]={}),e&&e===b.nodeName.toLowerCase())b=b[d]||b;else{if((k=z[f])&&k[0]===J&&k[1]===h)return l[2]=k[2];z[f]=l;if(l[2]=a(b,c,t))return!0}return!1}}function r(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function u(a,b,c,d,e){for(var f,g=[],h=0,t=a.length,k=null!=b;h<t;h++)if(f=a[h])if(!c||c(f,d,e))g.push(f),k&&b.push(h);return g}function v(a,c,e,f,g,h){f&&!f[D]&&(f=v(f));g&&!g[D]&&(g=v(g,h));return d(function(d,
h,t,k){var l,z,pa=[],m=[],n=h.length,P;if(!(P=d)){P=c||"*";for(var q=t.nodeType?[t]:t,Fa=[],p=0,I=q.length;p<I;p++)b(P,q[p],Fa);P=Fa}P=!a||!d&&c?P:u(P,pa,a,t,k);q=e?g||(d?a:n||f)?[]:h:P;e&&e(P,q,t,k);if(f)for(l=u(q,m),f(l,[],t,k),t=l.length;t--;)if(z=l[t])q[m[t]]=!(P[m[t]]=z);if(d){if(g||a){if(g){l=[];for(t=q.length;t--;)(z=q[t])&&l.push(P[t]=z);g(null,q=[],l,k)}for(t=q.length;t--;)(z=q[t])&&-1<(l=g?ya(d,z):pa[t])&&(d[l]=!(h[l]=z))}}else q=u(q===h?q.splice(n,q.length):q),g?g(null,h,q,k):qa.apply(h,
q)})}function Ea(a){var b,c,d,e=a.length,f=y.relative[a[0].type];c=f||y.relative[" "];for(var g=f?1:0,h=x(function(a){return a===b},c,!0),t=x(function(a){return-1<ya(b,a)},c,!0),k=[function(a,c,d){a=!f&&(d||c!==K)||((b=c).nodeType?h(a,c,d):t(a,c,d));b=null;return a}];g<e;g++)if(c=y.relative[a[g].type])k=[x(r(k),c)];else{c=y.filter[a[g].type].apply(null,a[g].matches);if(c[D]){for(d=++g;d<e&&!y.relative[a[d].type];d++);return v(1<g&&r(k),1<g&&p(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(W,
"$1"),c,g<d&&Ea(a.slice(g,d)),d<e&&Ea(a=a.slice(d)),d<e&&p(a))}k.push(c)}return r(k)}function F(a,c){var e=0<c.length,f=0<a.length,g=function(d,g,h,t,k){var l,z,pa,m=0,n="0",P=d&&[],q=[],p=K,I=d||f&&y.find.TAG("*",k),Fa=J+=null==p?1:Math.random()||.1,w=I.length;for(k&&(K=g==B||g||k);n!==w&&null!=(l=I[n]);n++){if(f&&l){z=0;g||l.ownerDocument==B||(C(l),h=!U);for(;pa=a[z++];)if(pa(l,g||B,h)){t.push(l);break}k&&(J=Fa)}e&&((l=!pa&&l)&&m--,d&&P.push(l))}m+=n;if(e&&n!==m){for(z=0;pa=c[z++];)pa(P,q,g,h);
if(d){if(0<m)for(;n--;)P[n]||q[n]||(q[n]=ka.call(t));q=u(q)}qa.apply(t,q);k&&!d&&0<q.length&&1<m+c.length&&b.uniqueSort(t)}k&&(J=Fa,K=p);return P};return e?d(g):g}var A,w,y,Ma,H,E,N,O,K,ra,G,C,B,S,U,M,L,R,Q,D="sizzle"+1*new Date,Z=a.document,J=0,Y=0,V=c(),X=c(),da=c(),T=c(),aa=function(a,b){a===b&&(G=!0);return 0},ia={}.hasOwnProperty,za=[],ka=za.pop,la=za.push,qa=za.push,ea=za.slice,ya=function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},ma=RegExp("[\\x20\\t\\r\\n\\f]+","g"),
W=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),na=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,fa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,oa=/[\x20\t\r\n\f]|>/,sa=/:((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,
wa=/^(?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+$/,ca={ID:/^#((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+)/,CLASS:/^\.((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+)/,TAG:/^((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+|[*])/,ATTR:/^\[[\x20\t\r\n\f]*((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+))|)[\x20\t\r\n\f]*\]/,
PSEUDO:/^:((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\[\da-fA-F]{1,6}[\x20\t\r\n\f]?|\\[^\r\n\f]|[\w-]|[^\x00-\x7f])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,
bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},xa=/HTML$/i,Aa=/^(?:input|select|textarea|button)$/i,Ba=/^h\d$/i,ba=/^[^{]+\{\s*\[native \w/,Ca=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ja=/[+~]/,ga=RegExp("\\\\[\\da-fA-F]{1,6}[\\x20\\t\\r\\n\\f]?|\\\\([^\\r\\n\\f])","g"),ha=function(a,
b){var c="0x"+a.slice(1)-65536;return b?b:0>c?String.fromCharCode(c+65536):String.fromCharCode(c>>10|55296,c&1023|56320)},ta=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\0-\x1f\x7f-\uFFFF\w-]/g,ua=function(a,b){return b?"\x00"===a?"\ufffd":a.slice(0,-1)+"\\"+a.charCodeAt(a.length-1).toString(16)+" ":"\\"+a},va=function(){C()},Da=x(function(a){return!0===a.disabled&&"fieldset"===a.nodeName.toLowerCase()},{dir:"parentNode",next:"legend"});try{qa.apply(za=ea.call(Z.childNodes),Z.childNodes),za[Z.childNodes.length].nodeType}catch(t){qa=
{apply:za.length?function(a,b){la.apply(a,ea.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}w=b.support={};H=b.isXML=function(a){var b=a&&(a.ownerDocument||a).documentElement;return!xa.test(a&&a.namespaceURI||b&&b.nodeName||"HTML")};C=b.setDocument=function(a){var b;a=a?a.ownerDocument||a:Z;if(a==B||9!==a.nodeType||!a.documentElement)return B;B=a;S=B.documentElement;U=!H(B);Z!=B&&(b=B.defaultView)&&b.top!==b&&(b.addEventListener?b.addEventListener("unload",va,!1):b.attachEvent&&
b.attachEvent("onunload",va));w.scope=f(function(a){S.appendChild(a).appendChild(B.createElement("div"));return"undefined"!==typeof a.querySelectorAll&&!a.querySelectorAll(":scope fieldset div").length});w.attributes=f(function(a){a.className="i";return!a.getAttribute("className")});w.getElementsByTagName=f(function(a){a.appendChild(B.createComment(""));return!a.getElementsByTagName("*").length});w.getElementsByClassName=ba.test(B.getElementsByClassName);w.getById=f(function(a){S.appendChild(a).id=
D;return!B.getElementsByName||!B.getElementsByName(D).length});w.getById?(y.filter.ID=function(a){var b=a.replace(ga,ha);return function(a){return a.getAttribute("id")===b}},y.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&U){var c=b.getElementById(a);return c?[c]:[]}}):(y.filter.ID=function(a){var b=a.replace(ga,ha);return function(a){return(a="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}},y.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&
U){var c,d,e,f=b.getElementById(a);if(f){if((c=f.getAttributeNode("id"))&&c.value===a)return[f];e=b.getElementsByName(a);for(d=0;f=e[d++];)if((c=f.getAttributeNode("id"))&&c.value===a)return[f]}return[]}});y.find.TAG=w.getElementsByTagName?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a);if(w.qsa)return b.querySelectorAll(a)}:function(a,b){var c,d=[],e=0,f=b.getElementsByTagName(a);if("*"===a){for(;c=f[e++];)1===c.nodeType&&d.push(c);return d}return f};
y.find.CLASS=w.getElementsByClassName&&function(a,b){if("undefined"!==typeof b.getElementsByClassName&&U)return b.getElementsByClassName(a)};L=[];M=[];if(w.qsa=ba.test(B.querySelectorAll))f(function(a){var b;S.appendChild(a).innerHTML="<a id='"+D+"'></a><select id='"+D+"-\r\\' msallowcapture=''><option selected=''></option></select>";a.querySelectorAll("[msallowcapture^='']").length&&M.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||M.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll("[id~="+D+"-]").length||M.push("~=");b=B.createElement("input");b.setAttribute("name","");a.appendChild(b);a.querySelectorAll("[name='']").length||M.push("\\[[\\x20\\t\\r\\n\\f]*name[\\x20\\t\\r\\n\\f]*=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll(":checked").length||M.push(":checked");a.querySelectorAll("a#"+D+"+*").length||M.push(".#.+[+~]");a.querySelectorAll("\\\f");M.push("[\\r\\n\\f]")}),f(function(a){a.innerHTML="<a href='' disabled='disabled'></a><select disabled='disabled'><option/></select>";
var b=B.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&M.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");2!==a.querySelectorAll(":enabled").length&&M.push(":enabled",":disabled");S.appendChild(a).disabled=!0;2!==a.querySelectorAll(":disabled").length&&M.push(":enabled",":disabled");a.querySelectorAll("*,:x");M.push(",.*:")});(w.matchesSelector=ba.test(R=S.matches||S.webkitMatchesSelector||S.mozMatchesSelector||S.oMatchesSelector||
S.msMatchesSelector))&&f(function(a){w.disconnectedMatch=R.call(a,"*");R.call(a,"[s!='']:x");L.push("!=",":((?:\\\\[\\da-fA-F]{1,6}[\\x20\\t\\r\\n\\f]?|\\\\[^\\r\\n\\f]|[\\w-]|[^\x00-\\x7f])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\[\\da-fA-F]{1,6}[\\x20\\t\\r\\n\\f]?|\\\\[^\\r\\n\\f]|[\\w-]|[^\x00-\\x7f])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\[\\da-fA-F]{1,6}[\\x20\\t\\r\\n\\f]?|\\\\[^\\r\\n\\f]|[\\w-]|[^\x00-\\x7f])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});
M=M.length&&new RegExp(M.join("|"));L=L.length&&new RegExp(L.join("|"));Q=(b=ba.test(S.compareDocumentPosition))||ba.test(S.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!!(d&&1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};aa=b?function(a,b){if(a===b)return G=!0,0;var c=!a.compareDocumentPosition-!b.compareDocumentPosition;
if(c)return c;c=(a.ownerDocument||a)==(b.ownerDocument||b)?a.compareDocumentPosition(b):1;return c&1||!w.sortDetached&&b.compareDocumentPosition(a)===c?a==B||a.ownerDocument==Z&&Q(Z,a)?-1:b==B||b.ownerDocument==Z&&Q(Z,b)?1:ra?ya(ra,a)-ya(ra,b):0:c&4?-1:1}:function(a,b){if(a===b)return G=!0,0;var c,d=0;c=a.parentNode;var e=b.parentNode,f=[a],g=[b];if(!c||!e)return a==B?-1:b==B?1:c?-1:e?1:ra?ya(ra,a)-ya(ra,b):0;if(c===e)return h(a,b);for(c=a;c=c.parentNode;)f.unshift(c);for(c=b;c=c.parentNode;)g.unshift(c);
for(;f[d]===g[d];)d++;return d?h(f[d],g[d]):f[d]==Z?-1:g[d]==Z?1:0};return B};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){C(a);if(!(!w.matchesSelector||!U||T[c+" "]||L&&L.test(c)||M&&M.test(c)))try{var d=R.call(a,c);if(d||w.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(P){T(c,!0)}return 0<b(c,B,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!=B&&C(a);return Q(a,b)};b.attr=function(a,b){(a.ownerDocument||a)!=B&&C(a);var c=
y.attrHandle[b.toLowerCase()],c=c&&ia.call(y.attrHandle,b.toLowerCase())?c(a,b,!U):void 0;return void 0!==c?c:w.attributes||!U?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.escape=function(a){return(a+"").replace(ta,ua)};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;G=!w.detectDuplicates;ra=!w.sortStable&&a.slice(0);a.sort(aa);if(G){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],
1)}ra=null;return a};Ma=b.getText=function(a){var b,c="",d=0;b=a.nodeType;if(!b)for(;b=a[d++];)c+=Ma(b);else if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=Ma(a)}else if(3===b||4===b)return a.nodeValue;return c};y=b.selectors={cacheLength:50,createPseudo:d,match:ca,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=
a[1].replace(ga,ha);a[3]=(a[3]||a[4]||a[5]||"").replace(ga,ha);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(ca.CHILD.test(a[0]))return null;a[3]?a[2]=a[4]||a[5]||"":c&&sa.test(c)&&(b=E(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length)&&(a[0]=a[0].slice(0,
b),a[2]=c.slice(0,b));return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(ga,ha).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=V[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),V(a,function(a){return b.test("string"===typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}))},ATTR:function(a,c,d){return function(e){e=b.attr(e,
a);if(null==e)return"!="===c;if(!c)return!0;e+="";return"="===c?e===d:"!="===c?e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e.replace(ma," ")+" ").indexOf(d):"|="===c?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,k){var l,n,t,m,q;c=f!==g?"nextSibling":"previousSibling";var z=
b.parentNode,p=h&&b.nodeName.toLowerCase();k=!k&&!h;l=!1;if(z){if(f){for(;c;){for(t=b;t=t[c];)if(h?t.nodeName.toLowerCase()===p:1===t.nodeType)return!1;q=c="only"===a&&!q&&"nextSibling"}return!0}q=[g?z.firstChild:z.lastChild];if(g&&k)for(t=z,n=t[D]||(t[D]={}),n=n[t.uniqueID]||(n[t.uniqueID]={}),l=n[a]||[],l=(m=l[0]===J&&l[1])&&l[2],t=m&&z.childNodes[m];t=++m&&t&&t[c]||(l=m=0)||q.pop();){if(1===t.nodeType&&++l&&t===b){n[a]=[J,m,l];break}}else if(k&&(t=b,n=t[D]||(t[D]={}),n=n[t.uniqueID]||(n[t.uniqueID]=
{}),l=n[a]||[],l=m=l[0]===J&&l[1]),!1===l)for(;(t=++m&&t&&t[c]||(l=m=0)||q.pop())&&((h?t.nodeName.toLowerCase()!==p:1!==t.nodeType)||!++l||(k&&(n=t[D]||(t[D]={}),n=n[t.uniqueID]||(n[t.uniqueID]={}),n[a]=[J,l]),t!==b)););l-=e;return l===d||0===l%d&&0<=l/d}}},PSEUDO:function(a,c){var e,f=y.pseudos[a]||y.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return f[D]?f(c):1<f.length?(e=[a,a,"",c],y.setFilters.hasOwnProperty(a.toLowerCase())?d(function(a,b){for(var d,e=f(a,c),g=e.length;g--;)d=
ya(a,e[g]),a[d]=!(b[d]=e[g])}):function(a){return f(a,0,e)}):f}},pseudos:{not:d(function(a){var b=[],c=[],e=N(a.replace(W,"$1"));return e[D]?d(function(a,b,c,d){d=e(a,null,d,[]);for(var f=a.length;f--;)if(c=d[f])a[f]=!(b[f]=c)}):function(a,d,f){b[0]=a;e(b,null,f,c);b[0]=null;return!c.pop()}}),has:d(function(a){return function(c){return 0<b(a,c).length}}),contains:d(function(a){a=a.replace(ga,ha);return function(b){return-1<(b.textContent||Ma(b)).indexOf(a)}}),lang:d(function(a){wa.test(a||"")||b.error("unsupported lang: "+
a);a=a.replace(ga,ha).toLowerCase();return function(b){var c;do if(c=U?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===S},focus:function(a){return a===B.activeElement&&(!B.hasFocus||B.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:n(!1),disabled:n(!0),checked:function(a){var b=
a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!y.pseudos.empty(a)},header:function(a){return Ba.test(a.nodeName)},input:function(a){return Aa.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},
text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:q(function(){return[0]}),last:q(function(a,b){return[b-1]}),eq:q(function(a,b,c){return[0>c?c+b:c]}),even:q(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:q(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:q(function(a,b,c){for(b=0>c?c+b:c>b?b:c;0<=--b;)a.push(b);return a}),gt:q(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);
return a})}};y.pseudos.nth=y.pseudos.eq;for(A in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})y.pseudos[A]=k(A);for(A in{submit:!0,reset:!0})y.pseudos[A]=l(A);m.prototype=y.filters=y.pseudos;y.setFilters=new m;E=b.tokenize=function(a,c){var d,e,f,g,h,l,k;if(h=X[a+" "])return c?0:h.slice(0);h=a;l=[];for(k=y.preFilter;h;){if(!d||(e=na.exec(h)))e&&(h=h.slice(e[0].length)||h),l.push(f=[]);d=!1;if(e=fa.exec(h))d=e.shift(),f.push({value:d,type:e[0].replace(W," ")}),h=h.slice(d.length);for(g in y.filter)!(e=
ca[g].exec(h))||k[g]&&!(e=k[g](e))||(d=e.shift(),f.push({value:d,type:g,matches:e}),h=h.slice(d.length));if(!d)break}return c?h.length:h?b.error(a):X(a,l).slice(0)};N=b.compile=function(a,b){var c,d=[],e=[],f=da[a+" "];if(!f){b||(b=E(a));for(c=b.length;c--;)f=Ea(b[c]),f[D]?d.push(f):e.push(f);f=da(a,F(e,d));f.selector=a}return f};O=b.select=function(a,b,c,d){var e,f,g,h,l="function"===typeof a&&a,k=!d&&E(a=l.selector||a);c=c||[];if(1===k.length){f=k[0]=k[0].slice(0);if(2<f.length&&"ID"===(g=f[0]).type&&
9===b.nodeType&&U&&y.relative[f[1].type]){b=(y.find.ID(g.matches[0].replace(ga,ha),b)||[])[0];if(!b)return c;l&&(b=b.parentNode);a=a.slice(f.shift().value.length)}for(e=ca.needsContext.test(a)?0:f.length;e--;){g=f[e];if(y.relative[h=g.type])break;if(h=y.find[h])if(d=h(g.matches[0].replace(ga,ha),ja.test(f[0].type)&&I(b.parentNode)||b)){f.splice(e,1);a=d.length&&p(f);if(!a)return qa.apply(c,d),c;break}}}(l||N(a,k))(d,b,!U,c,!b||ja.test(a)&&I(b.parentNode)||b);return c};w.sortStable=D.split("").sort(aa).join("")===
D;w.detectDuplicates=!!G;C();w.sortDetached=f(function(a){return a.compareDocumentPosition(B.createElement("fieldset"))&1});f(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});w.attributes&&f(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")})||g("value",function(a,b,c){if(!c&&"input"===
a.nodeName.toLowerCase())return a.defaultValue});f(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});return b}(p);d.find=aa;d.expr=aa.selectors;d.expr[":"]=d.expr.pseudos;d.uniqueSort=d.unique=aa.uniqueSort;d.text=aa.getText;d.isXMLDoc=aa.isXML;d.contains=
aa.contains;d.escapeSelector=aa.escape;var sa=function(a,b,c){for(var e=[],f=void 0!==c;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&d(a).is(c))break;e.push(a)}return e},Bb=function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c},Cb=d.expr.match.needsContext,Db=/^<([a-z][^\/\0>:\x20\t\r\n\f]*)[\x20\t\r\n\f]*\/?>(?:<\/\1>|)$/i;d.filter=function(a,b,c){var e=b[0];c&&(a=":not("+a+")");return 1===b.length&&1===e.nodeType?d.find.matchesSelector(e,a)?[e]:[]:d.find.matches(a,
d.grep(b,function(a){return 1===a.nodeType}))};d.fn.extend({find:function(a){var b,c,e=this.length,f=this;if("string"!==typeof a)return this.pushStack(d(a).filter(function(){for(b=0;b<e;b++)if(d.contains(f[b],this))return!0}));c=this.pushStack([]);for(b=0;b<e;b++)d.find(a,f[b],c);return 1<e?d.uniqueSort(c):c},filter:function(a){return this.pushStack(Na(this,a||[],!1))},not:function(a){return this.pushStack(Na(this,a||[],!0))},is:function(a){return!!Na(this,"string"===typeof a&&Cb.test(a)?d(a):a||
[],!1).length}});var Eb,kc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]+))$/;(d.fn.init=function(a,b,c){var e;if(!a)return this;c=c||Eb;if("string"===typeof a){e="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:kc.exec(a);if(!e||!e[1]&&b)return!b||b.jquery?(b||c).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof d?b[0]:b,d.merge(this,d.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:u,!0)),Db.test(e[1])&&d.isPlainObject(b))for(e in b)if(r(this[e]))this[e](b[e]);else this.attr(e,b[e])}else if(a=
u.getElementById(e[2]))this[0]=a,this.length=1;return this}return a.nodeType?(this[0]=a,this.length=1,this):r(a)?void 0!==c.ready?c.ready(a):a(d):d.makeArray(a,this)}).prototype=d.fn;Eb=d(u);var lc=/^(?:parents|prev(?:Until|All))/,mc={children:!0,contents:!0,next:!0,prev:!0};d.fn.extend({has:function(a){var b=d(a,this),c=b.length;return this.filter(function(){for(var a=0;a<c;a++)if(d.contains(this,b[a]))return!0})},closest:function(a,b){var c,e=0,f=this.length,g=[],h="string"!==typeof a&&d(a);if(!Cb.test(a))for(;e<
f;e++)for(c=this[e];c&&c!==b;c=c.parentNode)if(11>c.nodeType&&(h?-1<h.index(c):1===c.nodeType&&d.find.matchesSelector(c,a))){g.push(c);break}return this.pushStack(1<g.length?d.uniqueSort(g):g)},index:function(a){return a?"string"===typeof a?ua.call(d(a),this[0]):ua.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(d.uniqueSort(d.merge(this.get(),d(a,b))))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});
d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return sa(a,"parentNode")},parentsUntil:function(a,b,c){return sa(a,"parentNode",c)},next:function(a){return db(a,"nextSibling")},prev:function(a){return db(a,"previousSibling")},nextAll:function(a){return sa(a,"nextSibling")},prevAll:function(a){return sa(a,"previousSibling")},nextUntil:function(a,b,c){return sa(a,"nextSibling",c)},prevUntil:function(a,b,c){return sa(a,"previousSibling",c)},siblings:function(a){return Bb((a.parentNode||
{}).firstChild,a)},children:function(a){return Bb(a.firstChild)},contents:function(a){if(null!=a.contentDocument&&zb(a.contentDocument))return a.contentDocument;E(a,"template")&&(a=a.content||a);return d.merge([],a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=d.map(this,b,c);"Until"!==a.slice(-5)&&(e=c);e&&"string"===typeof e&&(f=d.filter(e,f));1<this.length&&(mc[a]||d.uniqueSort(f),lc.test(a)&&f.reverse());return this.pushStack(f)}});var R=/[^\x20\t\r\n\f]+/g;d.Callbacks=function(a){a=
"string"===typeof a?Tb(a):d.extend({},a);var b,c,e,f,g=[],h=[],k=-1,l=function(){f=f||a.once;for(e=b=!0;h.length;k=-1)for(c=h.shift();++k<g.length;)!1===g[k].apply(c[0],c[1])&&a.stopOnFalse&&(k=g.length,c=!1);a.memory||(c=!1);b=!1;f&&(g=c?[]:"")},n={add:function(){g&&(c&&!b&&(k=g.length-1,h.push(c)),function I(b){d.each(b,function(b,c){r(c)?a.unique&&n.has(c)||g.push(c):c&&c.length&&"string"!==H(c)&&I(c)})}(arguments),c&&!b&&l());return this},remove:function(){d.each(arguments,function(a,b){for(var c;-1<
(c=d.inArray(b,g,c));)g.splice(c,1),c<=k&&k--});return this},has:function(a){return a?-1<d.inArray(a,g):0<g.length},empty:function(){g&&(g=[]);return this},disable:function(){f=h=[];g=c="";return this},disabled:function(){return!g},lock:function(){f=h=[];c||b||(g=c="");return this},locked:function(){return!!f},fireWith:function(a,c){f||(c=c||[],c=[a,c.slice?c.slice():c],h.push(c),b||l());return this},fire:function(){n.fireWith(this,arguments);return this},fired:function(){return!!e}};return n};d.extend({Deferred:function(a){var b=
[["notify","progress",d.Callbacks("memory"),d.Callbacks("memory"),2],["resolve","done",d.Callbacks("once memory"),d.Callbacks("once memory"),0,"resolved"],["reject","fail",d.Callbacks("once memory"),d.Callbacks("once memory"),1,"rejected"]],c="pending",e={state:function(){return c},always:function(){f.done(arguments).fail(arguments);return this},"catch":function(a){return e.then(null,a)},pipe:function(){var a=arguments;return d.Deferred(function(c){d.each(b,function(b,d){var e=r(a[d[4]])&&a[d[4]];
f[d[1]](function(){var a=e&&e.apply(this,arguments);if(a&&r(a.promise))a.promise().progress(c.notify).done(c.resolve).fail(c.reject);else c[d[0]+"With"](this,e?[a]:arguments)})});a=null}).promise()},then:function(a,c,e){function f(a,b,c,e){return function(){var h=this,k=arguments,l=function(){var d,l;if(!(a<g)){d=c.apply(h,k);if(d===b.promise())throw new TypeError("Thenable self-resolution");l=d&&("object"===typeof d||"function"===typeof d)&&d.then;r(l)?e?l.call(d,f(g,b,la,e),f(g,b,va,e)):(g++,l.call(d,
f(g,b,la,e),f(g,b,va,e),f(g,b,la,b.notifyWith))):(c!==la&&(h=void 0,k=[d]),(e||b.resolveWith)(h,k))}},n=e?l:function(){try{l()}catch(Ea){d.Deferred.exceptionHook&&d.Deferred.exceptionHook(Ea,n.stackTrace),a+1>=g&&(c!==va&&(h=void 0,k=[Ea]),b.rejectWith(h,k))}};a?n():(d.Deferred.getStackHook&&(n.stackTrace=d.Deferred.getStackHook()),p.setTimeout(n))}}var g=0;return d.Deferred(function(d){b[0][3].add(f(0,d,r(e)?e:la,d.notifyWith));b[1][3].add(f(0,d,r(a)?a:la));b[2][3].add(f(0,d,r(c)?c:va))}).promise()},
promise:function(a){return null!=a?d.extend(a,e):e}},f={};d.each(b,function(a,d){var g=d[2],h=d[5];e[d[1]]=g.add;h&&g.add(function(){c=h},b[3-a][2].disable,b[3-a][3].disable,b[0][2].lock,b[0][3].lock);g.add(d[3].fire);f[d[0]]=function(){f[d[0]+"With"](this===f?void 0:this,arguments);return this};f[d[0]+"With"]=g.fireWith});e.promise(f);a&&a.call(f,f);return f},when:function(a){var b=arguments.length,c=b,e=Array(c),f=X.call(arguments),g=d.Deferred(),h=function(a){return function(c){e[a]=this;f[a]=
1<arguments.length?X.call(arguments):c;--b||g.resolveWith(e,f)}};if(1>=b&&(eb(a,g.done(h(c)).resolve,g.reject,!b),"pending"===g.state()||r(f[c]&&f[c].then)))return g.then();for(;c--;)eb(f[c],h(c),g.reject);return g.promise()}});var nc=/^(Eval|Internal|Range|Reference|Syntax|Type|URI)Error$/;d.Deferred.exceptionHook=function(a,b){p.console&&p.console.warn&&a&&nc.test(a.name)&&p.console.warn("jQuery.Deferred exception: "+a.message,a.stack,b)};d.readyException=function(a){p.setTimeout(function(){throw a;
})};var Za=d.Deferred();d.fn.ready=function(a){Za.then(a)["catch"](function(a){d.readyException(a)});return this};d.extend({isReady:!1,readyWait:1,ready:function(a){(!0===a?--d.readyWait:d.isReady)||(d.isReady=!0,!0!==a&&0<--d.readyWait||Za.resolveWith(u,[d]))}});d.ready.then=Za.then;"complete"===u.readyState||"loading"!==u.readyState&&!u.documentElement.doScroll?p.setTimeout(d.ready):(u.addEventListener("DOMContentLoaded",Da),p.addEventListener("load",Da));var V=function(a,b,c,e,f,g,h){var k=0,l=
a.length,n=null==c;if("object"===H(c))for(k in f=!0,c)V(a,b,k,c[k],!0,g,h);else if(void 0!==e&&(f=!0,r(e)||(h=!0),n&&(h?(b.call(a,e),b=null):(n=b,b=function(a,b,c){return n.call(d(a),c)})),b))for(;k<l;k++)b(a[k],c,h?e:e.call(a[k],k,b(a[k],c)));return f?a:n?b.call(a):l?b(a[0],c):g},Vb=/^-ms-/,Wb=/-([a-z])/g,Aa=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};wa.uid=1;wa.prototype={cache:function(a){var b=a[this.expando];b||(b={},Aa(a)&&(a.nodeType?a[this.expando]=b:Object.defineProperty(a,
this.expando,{value:b,configurable:!0})));return b},set:function(a,b,c){var d;a=this.cache(a);if("string"===typeof b)a[Q(b)]=c;else for(d in b)a[Q(d)]=b[d];return a},get:function(a,b){return void 0===b?this.cache(a):a[this.expando]&&a[this.expando][Q(b)]},access:function(a,b,c){if(void 0===b||b&&"string"===typeof b&&void 0===c)return this.get(a,b);this.set(a,b,c);return void 0!==c?c:b},remove:function(a,b){var c,e=a[this.expando];if(void 0!==e){if(void 0!==b)for(Array.isArray(b)?b=b.map(Q):(b=Q(b),
b=b in e?[b]:b.match(R)||[]),c=b.length;c--;)delete e[b[c]];if(void 0===b||d.isEmptyObject(e))a.nodeType?a[this.expando]=void 0:delete a[this.expando]}},hasData:function(a){a=a[this.expando];return void 0!==a&&!d.isEmptyObject(a)}};var x=new wa,N=new wa,Yb=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,Xb=/[A-Z]/g;d.extend({hasData:function(a){return N.hasData(a)||x.hasData(a)},data:function(a,b,c){return N.access(a,b,c)},removeData:function(a,b){N.remove(a,b)},_data:function(a,b,c){return x.access(a,b,c)},_removeData:function(a,
b){x.remove(a,b)}});d.fn.extend({data:function(a,b){var c,d,f,g=this[0],h=g&&g.attributes;if(void 0===a){if(this.length&&(f=N.get(g),1===g.nodeType&&!x.get(g,"hasDataAttrs"))){for(c=h.length;c--;)h[c]&&(d=h[c].name,0===d.indexOf("data-")&&(d=Q(d.slice(5)),fb(g,d,f[d])));x.set(g,"hasDataAttrs",!0)}return f}return"object"===typeof a?this.each(function(){N.set(this,a)}):V(this,function(b){var c;if(g&&void 0===b){c=N.get(g,a);if(void 0!==c)return c;c=fb(g,a);if(void 0!==c)return c}else this.each(function(){N.set(this,
a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){N.remove(this,a)})}});d.extend({queue:function(a,b,c){var e;if(a)return b=(b||"fx")+"queue",e=x.get(a,b),c&&(!e||Array.isArray(c)?e=x.access(a,b,d.makeArray(c)):e.push(c)),e||[]},dequeue:function(a,b){b=b||"fx";var c=d.queue(a,b),e=c.length,f=c.shift(),g=d._queueHooks(a,b),h=function(){d.dequeue(a,b)};"inprogress"===f&&(f=c.shift(),e--);f&&("fx"===b&&c.unshift("inprogress"),delete g.stop,f.call(a,h,g));
!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var c=b+"queueHooks";return x.get(a,c)||x.access(a,c,{empty:d.Callbacks("once memory").add(function(){x.remove(a,[b+"queue",c])})})}});d.fn.extend({queue:function(a,b){var c=2;"string"!==typeof a&&(b=a,a="fx",c--);return arguments.length<c?d.queue(this[0],a):void 0===b?this:this.each(function(){var c=d.queue(this,a,b);d._queueHooks(this,a);"fx"===a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,
a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var c,e=1,f=d.Deferred(),g=this,h=this.length,k=function(){--e||f.resolveWith(g,[g])};"string"!==typeof a&&(b=a,a=void 0);for(a=a||"fx";h--;)(c=x.get(g[h],a+"queueHooks"))&&c.empty&&(e++,c.empty.add(k));k();return f.promise(b)}});var Fb=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,ca=new RegExp("^(?:([+-])=|)("+Fb+")([a-z%]*)$","i"),J=["Top","Right","Bottom","Left"],ia=u.documentElement,ma=function(a){return d.contains(a.ownerDocument,
a)},oc={composed:!0};ia.getRootNode&&(ma=function(a){return d.contains(a.ownerDocument,a)||a.getRootNode(oc)===a.ownerDocument});var Ga=function(a,b){a=b||a;return"none"===a.style.display||""===a.style.display&&ma(a)&&"none"===d.css(a,"display")},hb={};d.fn.extend({show:function(){return ea(this,!0)},hide:function(){return ea(this)},toggle:function(a){return"boolean"===typeof a?a?this.show():this.hide():this.each(function(){Ga(this)?d(this).show():d(this).hide()})}});var Ba=/^(?:checkbox|radio)$/i,
jb=/<([a-z][^\/\0>\x20\t\r\n\f]*)/i,kb=/^$|^module$|\/(?:java|ecma)script/i;(function(){var a=u.createDocumentFragment().appendChild(u.createElement("div")),b=u.createElement("input");b.setAttribute("type","radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);v.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="<textarea>x</textarea>";v.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue;a.innerHTML="<option></option>";v.option=!!a.lastChild})();
var C={thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};C.tbody=C.tfoot=C.colgroup=C.caption=C.thead;C.th=C.td;v.option||(C.optgroup=C.option=[1,"<select multiple='multiple'>","</select>"]);var Zb=/<|&#?\w+;/,Gb=/^([^.]*)(?:\.(.+)|)/;d.event={global:{},add:function(a,b,c,e,f){var g,h,k,l,n,q,p,m,r;n=x.get(a);if(Aa(a))for(c.handler&&(g=c,c=g.handler,f=g.selector),
f&&d.find.matchesSelector(ia,f),c.guid||(c.guid=d.guid++),(l=n.events)||(l=n.events=Object.create(null)),(h=n.handle)||(h=n.handle=function(b){return"undefined"!==typeof d&&d.event.triggered!==b.type?d.event.dispatch.apply(a,arguments):void 0}),b=(b||"").match(R)||[""],n=b.length;n--;)k=Gb.exec(b[n])||[],m=q=k[1],r=(k[2]||"").split(".").sort(),m&&(k=d.event.special[m]||{},m=(f?k.delegateType:k.bindType)||m,k=d.event.special[m]||{},q=d.extend({type:m,origType:q,data:e,handler:c,guid:c.guid,selector:f,
needsContext:f&&d.expr.match.needsContext.test(f),namespace:r.join(".")},g),(p=l[m])||(p=l[m]=[],p.delegateCount=0,k.setup&&!1!==k.setup.call(a,e,r,h)||a.addEventListener&&a.addEventListener(m,h)),k.add&&(k.add.call(a,q),q.handler.guid||(q.handler.guid=c.guid)),f?p.splice(p.delegateCount++,0,q):p.push(q),d.event.global[m]=!0)},remove:function(a,b,c,e,f){var g,h,k,l,n,q,p,m,r,u,v,A=x.hasData(a)&&x.get(a);if(A&&(l=A.events)){b=(b||"").match(R)||[""];for(n=b.length;n--;)if(k=Gb.exec(b[n])||[],r=v=k[1],
u=(k[2]||"").split(".").sort(),r){p=d.event.special[r]||{};r=(e?p.delegateType:p.bindType)||r;m=l[r]||[];k=k[2]&&new RegExp("(^|\\.)"+u.join("\\.(?:.*\\.|)")+"(\\.|$)");for(h=g=m.length;g--;)q=m[g],!f&&v!==q.origType||c&&c.guid!==q.guid||k&&!k.test(q.namespace)||e&&e!==q.selector&&("**"!==e||!q.selector)||(m.splice(g,1),q.selector&&m.delegateCount--,p.remove&&p.remove.call(a,q));h&&!m.length&&(p.teardown&&!1!==p.teardown.call(a,u,A.handle)||d.removeEvent(a,r,A.handle),delete l[r])}else for(r in l)d.event.remove(a,
r+b[n],c,e,!0);d.isEmptyObject(l)&&x.remove(a,"handle events")}},dispatch:function(a){var b,c,e,f,g,h=Array(arguments.length),k=d.event.fix(a);c=(x.get(this,"events")||Object.create(null))[k.type]||[];var l=d.event.special[k.type]||{};h[0]=k;for(b=1;b<arguments.length;b++)h[b]=arguments[b];k.delegateTarget=this;if(!l.preDispatch||!1!==l.preDispatch.call(this,k)){g=d.event.handlers.call(this,k,c);for(b=0;(f=g[b++])&&!k.isPropagationStopped();)for(k.currentTarget=f.elem,c=0;(e=f.handlers[c++])&&!k.isImmediatePropagationStopped();)if(!k.rnamespace||
!1===e.namespace||k.rnamespace.test(e.namespace))k.handleObj=e,k.data=e.data,e=((d.event.special[e.origType]||{}).handle||e.handler).apply(f.elem,h),void 0!==e&&!1===(k.result=e)&&(k.preventDefault(),k.stopPropagation());l.postDispatch&&l.postDispatch.call(this,k);return k.result}},handlers:function(a,b){var c,e,f,g,h,k=[],l=b.delegateCount,n=a.target;if(l&&n.nodeType&&!("click"===a.type&&1<=a.button))for(;n!==this;n=n.parentNode||this)if(1===n.nodeType&&("click"!==a.type||!0!==n.disabled)){g=[];
h={};for(c=0;c<l;c++)e=b[c],f=e.selector+" ",void 0===h[f]&&(h[f]=e.needsContext?-1<d(f,this).index(n):d.find(f,this,null,[n]).length),h[f]&&g.push(e);g.length&&k.push({elem:n,handlers:g})}l<b.length&&k.push({elem:this,handlers:b.slice(l)});return k},addProp:function(a,b){Object.defineProperty(d.Event.prototype,a,{enumerable:!0,configurable:!0,get:r(b)?function(){if(this.originalEvent)return b(this.originalEvent)}:function(){if(this.originalEvent)return this.originalEvent[a]},set:function(b){Object.defineProperty(this,
a,{enumerable:!0,configurable:!0,writable:!0,value:b})}})},fix:function(a){return a[d.expando]?a:new d.Event(a)},special:{load:{noBubble:!0},click:{setup:function(a){a=this||a;Ba.test(a.type)&&a.click&&E(a,"input")&&Ha(a,"click",W);return!1},trigger:function(a){a=this||a;Ba.test(a.type)&&a.click&&E(a,"input")&&Ha(a,"click");return!0},_default:function(a){a=a.target;return Ba.test(a.type)&&a.click&&E(a,"input")&&x.get(a,"click")||E(a,"a")}},beforeunload:{postDispatch:function(a){void 0!==a.result&&
a.originalEvent&&(a.originalEvent.returnValue=a.result)}}}};d.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c)};d.Event=function(a,b){if(!(this instanceof d.Event))return new d.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||void 0===a.defaultPrevented&&!1===a.returnValue?W:na,this.target=a.target&&3===a.target.nodeType?a.target.parentNode:a.target,this.currentTarget=a.currentTarget,this.relatedTarget=a.relatedTarget):
this.type=a;b&&d.extend(this,b);this.timeStamp=a&&a.timeStamp||Date.now();this[d.expando]=!0};d.Event.prototype={constructor:d.Event,isDefaultPrevented:na,isPropagationStopped:na,isImmediatePropagationStopped:na,isSimulated:!1,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=W;a&&!this.isSimulated&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=W;a&&!this.isSimulated&&a.stopPropagation()},stopImmediatePropagation:function(){var a=
this.originalEvent;this.isImmediatePropagationStopped=W;a&&!this.isSimulated&&a.stopImmediatePropagation();this.stopPropagation()}};d.each({altKey:!0,bubbles:!0,cancelable:!0,changedTouches:!0,ctrlKey:!0,detail:!0,eventPhase:!0,metaKey:!0,pageX:!0,pageY:!0,shiftKey:!0,view:!0,"char":!0,code:!0,charCode:!0,key:!0,keyCode:!0,button:!0,buttons:!0,clientX:!0,clientY:!0,offsetX:!0,offsetY:!0,pointerId:!0,pointerType:!0,screenX:!0,screenY:!0,targetTouches:!0,toElement:!0,touches:!0,which:!0},d.event.addProp);
d.each({focus:"focusin",blur:"focusout"},function(a,b){d.event.special[a]={setup:function(){Ha(this,a,$b);return!1},trigger:function(){Ha(this,a);return!0},_default:function(){return!0},delegateType:b}});d.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var c,f=a.relatedTarget,g=a.handleObj;if(!f||f!==this&&!d.contains(this,f))a.type=g.origType,c=g.handler.apply(this,
arguments),a.type=b;return c}}});d.fn.extend({on:function(a,b,c,d){return Pa(this,a,b,c,d)},one:function(a,b,c,d){return Pa(this,a,b,c,d,1)},off:function(a,b,c){var e;if(a&&a.preventDefault&&a.handleObj)return e=a.handleObj,d(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler),this;if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)c=b,b=void 0;!1===c&&(c=na);return this.each(function(){d.event.remove(this,a,
c,b)})}});var pc=/<script|<style|<link/i,cc=/checked\s*(?:[^=]|=\s*.checked.)/i,dc=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g;d.extend({htmlPrefilter:function(a){return a},clone:function(a,b,c){var e,f,g,h,k=a.cloneNode(!0),l=ma(a);if(!(v.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||d.isXMLDoc(a)))for(h=O(k),g=O(a),e=0,f=g.length;e<f;e++){var n=g[e],q=h[e],p=q.nodeName.toLowerCase();if("input"===p&&Ba.test(n.type))q.checked=n.checked;else if("input"===p||"textarea"===p)q.defaultValue=n.defaultValue}if(b)if(c)for(g=
g||O(a),h=h||O(k),e=0,f=g.length;e<f;e++)mb(g[e],h[e]);else mb(a,k);h=O(k,"script");0<h.length&&Oa(h,!l&&O(a,"script"));return k},cleanData:function(a){for(var b,c,e,f=d.event.special,g=0;void 0!==(c=a[g]);g++)if(Aa(c)){if(b=c[x.expando]){if(b.events)for(e in b.events)f[e]?d.event.remove(c,e):d.removeEvent(c,e,b.handle);c[x.expando]=void 0}c[N.expando]&&(c[N.expando]=void 0)}}});d.fn.extend({detach:function(a){return ob(this,a,!0)},remove:function(a){return ob(this,a)},text:function(a){return V(this,
function(a){return void 0===a?d.text(this):this.empty().each(function(){if(1===this.nodeType||11===this.nodeType||9===this.nodeType)this.textContent=a})},null,a,arguments.length)},append:function(){return fa(this,arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||lb(this,a).appendChild(a)})},prepend:function(){return fa(this,arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=lb(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return fa(this,
arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return fa(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(d.cleanData(O(a,!1)),a.textContent="");return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return d.clone(this,a,b)})},html:function(a){return V(this,function(a){var b=this[0]||{},e=0,f=this.length;
if(void 0===a&&1===b.nodeType)return b.innerHTML;if("string"===typeof a&&!pc.test(a)&&!C[(jb.exec(a)||["",""])[1].toLowerCase()]){a=d.htmlPrefilter(a);try{for(;e<f;e++)b=this[e]||{},1===b.nodeType&&(d.cleanData(O(b,!1)),b.innerHTML=a);b=0}catch(g){}}b&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=[];return fa(this,arguments,function(b){var c=this.parentNode;0>d.inArray(this,a)&&(d.cleanData(O(this)),c&&c.replaceChild(b,this))},a)}});d.each({appendTo:"append",prependTo:"prepend",
insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(a){for(var c=[],f=d(a),g=f.length-1,h=0;h<=g;h++)a=h===g?this:this.clone(!0),d(f[h])[b](a),Ya.apply(c,a.get());return this.pushStack(c)}});var Qa=new RegExp("^("+Fb+")(?!px)[a-z%]+$","i"),Ia=function(a){var b=a.ownerDocument.defaultView;b&&b.opener||(b=p);return b.getComputedStyle(a)},Hb=function(a,b,c){var d,f={};for(d in b)f[d]=a.style[d],a.style[d]=b[d];c=c.call(a);for(d in b)a.style[d]=f[d];return c},
ec=new RegExp(J.join("|"),"i");(function(){function a(){if(l){k.style.cssText="position:absolute;left:-11111px;width:60px;margin-top:1px;padding:0;border:0";l.style.cssText="position:relative;display:block;box-sizing:border-box;overflow:scroll;margin:auto;border:1px;padding:1px;width:60%;top:1%";ia.appendChild(k).appendChild(l);var a=p.getComputedStyle(l);b="1%"!==a.top;h=12===Math.round(parseFloat(a.marginLeft));l.style.right="60%";f=36===Math.round(parseFloat(a.right));c=36===Math.round(parseFloat(a.width));
l.style.position="absolute";e=12===Math.round(parseFloat(l.offsetWidth/3));ia.removeChild(k);l=null}}var b,c,e,f,g,h,k=u.createElement("div"),l=u.createElement("div");l.style&&(l.style.backgroundClip="content-box",l.cloneNode(!0).style.backgroundClip="",v.clearCloneStyle="content-box"===l.style.backgroundClip,d.extend(v,{boxSizingReliable:function(){a();return c},pixelBoxStyles:function(){a();return f},pixelPosition:function(){a();return b},reliableMarginLeft:function(){a();return h},scrollboxSize:function(){a();
return e},reliableTrDimensions:function(){var a,b,c;null==g&&(a=u.createElement("table"),b=u.createElement("tr"),c=u.createElement("div"),a.style.cssText="position:absolute;left:-11111px;border-collapse:separate",b.style.cssText="border:1px solid",b.style.height="1px",c.style.height="9px",c.style.display="block",ia.appendChild(a).appendChild(b).appendChild(c),c=p.getComputedStyle(b),g=parseInt(c.height,10)+parseInt(c.borderTopWidth,10)+parseInt(c.borderBottomWidth,10)===b.offsetHeight,ia.removeChild(a));
return g}}))})();var sb=["Webkit","Moz","ms"],rb=u.createElement("div").style,qb={},qc=/^(none|table(?!-c[ea]).+)/,Ib=/^--/,rc={position:"absolute",visibility:"hidden",display:"block"},Jb={letterSpacing:"0",fontWeight:"400"};d.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=xa(a,"opacity");return""===c?"1":c}}}},cssNumber:{animationIterationCount:!0,columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,gridArea:!0,gridColumn:!0,gridColumnEnd:!0,gridColumnStart:!0,gridRow:!0,
gridRowEnd:!0,gridRowStart:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{},style:function(a,b,c,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g,h,k=Q(b),l=Ib.test(b),n=a.style;l||(b=Ra(k));h=d.cssHooks[b]||d.cssHooks[k];if(void 0!==c)g=typeof c,"string"===g&&(f=ca.exec(c))&&f[1]&&(c=gb(a,b,f),g="number"),null!=c&&c===c&&("number"!==g||l||(c+=f&&f[3]||(d.cssNumber[k]?"":"px")),v.clearCloneStyle||""!==c||0!==b.indexOf("background")||(n[b]="inherit"),
h&&"set"in h&&void 0===(c=h.set(a,c,e))||(l?n.setProperty(b,c):n[b]=c));else return h&&"get"in h&&void 0!==(f=h.get(a,!1,e))?f:n[b]}},css:function(a,b,c,e){var f,g;g=Q(b);Ib.test(b)||(b=Ra(g));(g=d.cssHooks[b]||d.cssHooks[g])&&"get"in g&&(f=g.get(a,!0,c));void 0===f&&(f=xa(a,b,e));"normal"===f&&b in Jb&&(f=Jb[b]);return""===c||c?(a=parseFloat(f),!0===c||isFinite(a)?a||0:f):f}});d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(a,e,f){if(e)return!qc.test(d.css(a,"display"))||a.getClientRects().length&&
a.getBoundingClientRect().width?ub(a,b,f):Hb(a,rc,function(){return ub(a,b,f)})},set:function(a,e,f){var c,h=Ia(a),k=!v.scrollboxSize()&&"absolute"===h.position,l=(k||f)&&"border-box"===d.css(a,"boxSizing",!1,h);f=f?Sa(a,b,f,l,h):0;l&&k&&(f-=Math.ceil(a["offset"+b[0].toUpperCase()+b.slice(1)]-parseFloat(h[b])-Sa(a,b,"border",!1,h)-.5));f&&(c=ca.exec(e))&&"px"!==(c[3]||"px")&&(a.style[b]=e,e=d.css(a,b));return tb(a,e,f)}}});d.cssHooks.marginLeft=pb(v.reliableMarginLeft,function(a,b){if(b)return(parseFloat(xa(a,
"marginLeft"))||a.getBoundingClientRect().left-Hb(a,{marginLeft:0},function(){return a.getBoundingClientRect().left}))+"px"});d.each({margin:"",padding:"",border:"Width"},function(a,b){d.cssHooks[a+b]={expand:function(c){var d=0,f={};for(c="string"===typeof c?c.split(" "):[c];4>d;d++)f[a+J[d]+b]=c[d]||c[d-2]||c[0];return f}};"margin"!==a&&(d.cssHooks[a+b].set=tb)});d.fn.extend({css:function(a,b){return V(this,function(a,b,f){var c,e={},k=0;if(Array.isArray(b)){f=Ia(a);for(c=b.length;k<c;k++)e[b[k]]=
d.css(a,b[k],!1,f);return e}return void 0!==f?d.style(a,b,f):d.css(a,b)},a,b,1<arguments.length)}});d.Tween=K;K.prototype={constructor:K,init:function(a,b,c,e,f,g){this.elem=a;this.prop=c;this.easing=f||d.easing._default;this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(d.cssNumber[c]?"":"px")},cur:function(){var a=K.propHooks[this.prop];return a&&a.get?a.get(this):K.propHooks._default.get(this)},run:function(a){var b,c=K.propHooks[this.prop];this.pos=this.options.duration?b=
d.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&this.options.step.call(this.elem,this.now,this);c&&c.set?c.set(this):K.propHooks._default.set(this);return this}};K.prototype.init.prototype=K.prototype;K.propHooks={_default:{get:function(a){return 1!==a.elem.nodeType||null!=a.elem[a.prop]&&null==a.elem.style[a.prop]?a.elem[a.prop]:(a=d.css(a.elem,a.prop,""))&&"auto"!==a?a:0},set:function(a){if(d.fx.step[a.prop])d.fx.step[a.prop](a);
else 1!==a.elem.nodeType||!d.cssHooks[a.prop]&&null==a.elem.style[Ra(a.prop)]?a.elem[a.prop]=a.now:d.style(a.elem,a.prop,a.now+a.unit)}}};K.propHooks.scrollTop=K.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};d.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2},_default:"swing"};d.fx=K.prototype.init;d.fx.step={};var oa,Ja,sc=/^(?:toggle|show|hide)$/,tc=/queueHooks$/;d.Animation=d.extend(L,{tweeners:{"*":[function(a,
b){var c=this.createTween(a,b);gb(c.elem,a,ca.exec(b),c);return c}]},tweener:function(a,b){r(a)?(b=a,a=["*"]):a=a.match(R);for(var c,d=0,f=a.length;d<f;d++)c=a[d],L.tweeners[c]=L.tweeners[c]||[],L.tweeners[c].unshift(b)},prefilters:[function(a,b,c){var e,f,g,h,k,l,n;n="width"in b||"height"in b;var p=this,r={},m=a.style,u=a.nodeType&&Ga(a),v=x.get(a,"fxshow");c.queue||(h=d._queueHooks(a,"fx"),null==h.unqueued&&(h.unqueued=0,k=h.empty.fire,h.empty.fire=function(){h.unqueued||k()}),h.unqueued++,p.always(function(){p.always(function(){h.unqueued--;
d.queue(a,"fx").length||h.empty.fire()})}));for(e in b)if(f=b[e],sc.test(f)){delete b[e];g=g||"toggle"===f;if(f===(u?"hide":"show"))if("show"===f&&v&&void 0!==v[e])u=!0;else continue;r[e]=v&&v[e]||d.style(a,e)}if((b=!d.isEmptyObject(b))||!d.isEmptyObject(r))for(e in n&&1===a.nodeType&&(c.overflow=[m.overflow,m.overflowX,m.overflowY],l=v&&v.display,null==l&&(l=x.get(a,"display")),n=d.css(a,"display"),"none"===n&&(l?n=l:(ea([a],!0),l=a.style.display||l,n=d.css(a,"display"),ea([a]))),("inline"===n||
"inline-block"===n&&null!=l)&&"none"===d.css(a,"float")&&(b||(p.done(function(){m.display=l}),null==l&&(n=m.display,l="none"===n?"":n)),m.display="inline-block")),c.overflow&&(m.overflow="hidden",p.always(function(){m.overflow=c.overflow[0];m.overflowX=c.overflow[1];m.overflowY=c.overflow[2]})),b=!1,r)b||(v?"hidden"in v&&(u=v.hidden):v=x.access(a,"fxshow",{display:l}),g&&(v.hidden=!u),u&&ea([a],!0),p.done(function(){u||ea([a]);x.remove(a,"fxshow");for(e in r)d.style(a,e,r[e])})),b=wb(u?v[e]:0,e,p),
e in v||(v[e]=b.start,u&&(b.end=b.start,b.start=0))}],prefilter:function(a,b){b?L.prefilters.unshift(a):L.prefilters.push(a)}});d.speed=function(a,b,c){var e=a&&"object"===typeof a?d.extend({},a):{complete:c||!c&&b||r(a)&&a,duration:a,easing:c&&b||b&&!r(b)&&b};d.fx.off?e.duration=0:"number"!==typeof e.duration&&(e.duration=e.duration in d.fx.speeds?d.fx.speeds[e.duration]:d.fx.speeds._default);if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(){r(e.old)&&e.old.call(this);
e.queue&&d.dequeue(this,e.queue)};return e};d.fn.extend({fadeTo:function(a,b,c,d){return this.filter(Ga).css("opacity",0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,e){var f=d.isEmptyObject(a),g=d.speed(b,c,e);b=function(){var b=L(this,d.extend({},a),g);(f||x.get(this,"finish"))&&b.stop(!0)};b.finish=b;return f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,c){var e=function(a){var b=a.stop;delete a.stop;b(c)};"string"!==typeof a&&(c=b,b=a,a=void 0);b&&this.queue(a||
"fx",[]);return this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=d.timers,k=x.get(this);if(g)k[g]&&k[g].stop&&e(k[g]);else for(g in k)k[g]&&k[g].stop&&tc.test(g)&&e(k[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(c),b=!1,h.splice(g,1));!b&&c||d.dequeue(this,a)})},finish:function(a){!1!==a&&(a=a||"fx");return this.each(function(){var b,c=x.get(this),e=c[a+"queue"];b=c[a+"queueHooks"];var f=d.timers,g=e?e.length:0;c.finish=!0;d.queue(this,a,[]);b&&b.stop&&
b.stop.call(this,!0);for(b=f.length;b--;)f[b].elem===this&&f[b].queue===a&&(f[b].anim.stop(!0),f.splice(b,1));for(b=0;b<g;b++)e[b]&&e[b].finish&&e[b].finish.call(this);delete c.finish})}});d.each(["toggle","show","hide"],function(a,b){var c=d.fn[b];d.fn[b]=function(a,d,g){return null==a||"boolean"===typeof a?c.apply(this,arguments):this.animate(Ka(b,!0),a,d,g)}});d.each({slideDown:Ka("show"),slideUp:Ka("hide"),slideToggle:Ka("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},
function(a,b){d.fn[a]=function(a,d,f){return this.animate(b,a,d,f)}});d.timers=[];d.fx.tick=function(){var a,b=0,c=d.timers;for(oa=Date.now();b<c.length;b++)a=c[b],a()||c[b]!==a||c.splice(b--,1);c.length||d.fx.stop();oa=void 0};d.fx.timer=function(a){d.timers.push(a);d.fx.start()};d.fx.interval=13;d.fx.start=function(){Ja||(Ja=!0,Ta())};d.fx.stop=function(){Ja=null};d.fx.speeds={slow:600,fast:200,_default:400};d.fn.delay=function(a,b){a=d.fx?d.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,
d){var c=p.setTimeout(b,a);d.stop=function(){p.clearTimeout(c)}})};(function(){var a=u.createElement("input"),b=u.createElement("select").appendChild(u.createElement("option"));a.type="checkbox";v.checkOn=""!==a.value;v.optSelected=b.selected;a=u.createElement("input");a.value="t";a.type="radio";v.radioValue="t"===a.value})();var Kb,ba=d.expr.attrHandle;d.fn.extend({attr:function(a,b){return V(this,d.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,
a)})}});d.extend({attr:function(a,b,c){var e,f,g=a.nodeType;if(3!==g&&8!==g&&2!==g){if("undefined"===typeof a.getAttribute)return d.prop(a,b,c);1===g&&d.isXMLDoc(a)||(f=d.attrHooks[b.toLowerCase()]||(d.expr.match.bool.test(b)?Kb:void 0));if(void 0!==c){if(null===c){d.removeAttr(a,b);return}if(f&&"set"in f&&void 0!==(e=f.set(a,c,b)))return e;a.setAttribute(b,c+"");return c}if(f&&"get"in f&&null!==(e=f.get(a,b)))return e;e=d.find.attr(a,b);return null==e?void 0:e}},attrHooks:{type:{set:function(a,b){if(!v.radioValue&&
"radio"===b&&E(a,"input")){var c=a.value;a.setAttribute("type",b);c&&(a.value=c);return b}}}},removeAttr:function(a,b){var c,d=0,f=b&&b.match(R);if(f&&1===a.nodeType)for(;c=f[d++];)a.removeAttribute(c)}});Kb={set:function(a,b,c){!1===b?d.removeAttr(a,c):a.setAttribute(c,c);return c}};d.each(d.expr.match.bool.source.match(/\w+/g),function(a,b){var c=ba[b]||d.find.attr;ba[b]=function(a,b,d){var e,f,g=b.toLowerCase();d||(f=ba[g],ba[g]=e,e=null!=c(a,b,d)?g:null,ba[g]=f);return e}});var uc=/^(?:input|select|textarea|button)$/i,
vc=/^(?:a|area)$/i;d.fn.extend({prop:function(a,b){return V(this,d.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[d.propFix[a]||a]})}});d.extend({prop:function(a,b,c){var e,f,g=a.nodeType;if(3!==g&&8!==g&&2!==g)return 1===g&&d.isXMLDoc(a)||(b=d.propFix[b]||b,f=d.propHooks[b]),void 0!==c?f&&"set"in f&&void 0!==(e=f.set(a,c,b))?e:a[b]=c:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b]},propHooks:{tabIndex:{get:function(a){var b=d.find.attr(a,"tabindex");return b?
parseInt(b,10):uc.test(a.nodeName)||vc.test(a.nodeName)&&a.href?0:-1}}},propFix:{"for":"htmlFor","class":"className"}});v.optSelected||(d.propHooks.selected={get:function(a){(a=a.parentNode)&&a.parentNode&&a.parentNode.selectedIndex;return null},set:function(a){if(a=a.parentNode)a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex}});d.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){d.propFix[this.toLowerCase()]=
this});d.fn.extend({addClass:function(a){var b,c,e,f,g,h,k=0;if(r(a))return this.each(function(b){d(this).addClass(a.call(this,b,T(this)))});b=Ua(a);if(b.length)for(;c=this[k++];)if(f=T(c),e=1===c.nodeType&&" "+da(f)+" "){for(h=0;g=b[h++];)0>e.indexOf(" "+g+" ")&&(e+=g+" ");e=da(e);f!==e&&c.setAttribute("class",e)}return this},removeClass:function(a){var b,c,e,f,g,h,k=0;if(r(a))return this.each(function(b){d(this).removeClass(a.call(this,b,T(this)))});if(!arguments.length)return this.attr("class",
"");b=Ua(a);if(b.length)for(;c=this[k++];)if(f=T(c),e=1===c.nodeType&&" "+da(f)+" "){for(h=0;g=b[h++];)for(;-1<e.indexOf(" "+g+" ");)e=e.replace(" "+g+" "," ");e=da(e);f!==e&&c.setAttribute("class",e)}return this},toggleClass:function(a,b){var c=typeof a,e="string"===c||Array.isArray(a);return"boolean"===typeof b&&e?b?this.addClass(a):this.removeClass(a):r(a)?this.each(function(c){d(this).toggleClass(a.call(this,c,T(this),b),b)}):this.each(function(){var b,g,h,k;if(e)for(g=0,h=d(this),k=Ua(a);b=k[g++];)h.hasClass(b)?
h.removeClass(b):h.addClass(b);else if(void 0===a||"boolean"===c)(b=T(this))&&x.set(this,"__className__",b),this.setAttribute&&this.setAttribute("class",b||!1===a?"":x.get(this,"__className__")||"")})},hasClass:function(a){var b,c=0;for(a=" "+a+" ";b=this[c++];)if(1===b.nodeType&&-1<(" "+da(T(b))+" ").indexOf(a))return!0;return!1}});var wc=/\r/g;d.fn.extend({val:function(a){var b,c,e,f=this[0];if(arguments.length)return e=r(a),this.each(function(c){1===this.nodeType&&(c=e?a.call(this,c,d(this).val()):
a,null==c?c="":"number"===typeof c?c+="":Array.isArray(c)&&(c=d.map(c,function(a){return null==a?"":a+""})),b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&void 0!==b.set(this,c,"value")||(this.value=c))});if(f){if((b=d.valHooks[f.type]||d.valHooks[f.nodeName.toLowerCase()])&&"get"in b&&void 0!==(c=b.get(f,"value")))return c;c=f.value;return"string"===typeof c?c.replace(wc,""):null==c?"":c}}});d.extend({valHooks:{option:{get:function(a){var b=d.find.attr(a,"value");
return null!=b?b:da(d.text(a))}},select:{get:function(a){var b,c=a.options,e=a.selectedIndex,f="select-one"===a.type,g=f?null:[],h=f?e+1:c.length;for(a=0>e?h:f?e:0;a<h;a++)if(b=c[a],!(!b.selected&&a!==e||b.disabled||b.parentNode.disabled&&E(b.parentNode,"optgroup"))){b=d(b).val();if(f)return b;g.push(b)}return g},set:function(a,b){for(var c,e,f=a.options,g=d.makeArray(b),h=f.length;h--;)if(e=f[h],e.selected=-1<d.inArray(d.valHooks.option.get(e),g))c=!0;c||(a.selectedIndex=-1);return g}}}});d.each(["radio",
"checkbox"],function(){d.valHooks[this]={set:function(a,b){if(Array.isArray(b))return a.checked=-1<d.inArray(d(a).val(),b)}};v.checkOn||(d.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});v.focusin="onfocusin"in p;var Lb=/^(?:focusinfocus|focusoutblur)$/,Mb=function(a){a.stopPropagation()};d.extend(d.event,{trigger:function(a,b,c,e){var f,g,h,k,l,n,q,v=[c||u],m=La.call(a,"type")?a.type:a;n=La.call(a,"namespace")?a.namespace.split("."):[];g=q=f=c=c||u;if(3!==c.nodeType&&
8!==c.nodeType&&!Lb.test(m+d.event.triggered)&&(-1<m.indexOf(".")&&(n=m.split("."),m=n.shift(),n.sort()),k=0>m.indexOf(":")&&"on"+m,a=a[d.expando]?a:new d.Event(m,"object"===typeof a&&a),a.isTrigger=e?2:3,a.namespace=n.join("."),a.rnamespace=a.namespace?new RegExp("(^|\\.)"+n.join("\\.(?:.*\\.|)")+"(\\.|$)"):null,a.result=void 0,a.target||(a.target=c),b=null==b?[a]:d.makeArray(b,[a]),n=d.event.special[m]||{},e||!n.trigger||!1!==n.trigger.apply(c,b))){if(!e&&!n.noBubble&&!ka(c)){h=n.delegateType||
m;Lb.test(h+m)||(g=g.parentNode);for(;g;g=g.parentNode)v.push(g),f=g;f===(c.ownerDocument||u)&&v.push(f.defaultView||f.parentWindow||p)}for(f=0;(g=v[f++])&&!a.isPropagationStopped();)q=g,a.type=1<f?h:n.bindType||m,(l=(x.get(g,"events")||Object.create(null))[a.type]&&x.get(g,"handle"))&&l.apply(g,b),(l=k&&g[k])&&l.apply&&Aa(g)&&(a.result=l.apply(g,b),!1===a.result&&a.preventDefault());a.type=m;e||a.isDefaultPrevented()||n._default&&!1!==n._default.apply(v.pop(),b)||!Aa(c)||!k||!r(c[m])||ka(c)||((f=
c[k])&&(c[k]=null),d.event.triggered=m,a.isPropagationStopped()&&q.addEventListener(m,Mb),c[m](),a.isPropagationStopped()&&q.removeEventListener(m,Mb),d.event.triggered=void 0,f&&(c[k]=f));return a.result}},simulate:function(a,b,c){a=d.extend(new d.Event,c,{type:a,isSimulated:!0});d.event.trigger(a,null,b)}});d.fn.extend({trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},triggerHandler:function(a,b){var c=this[0];if(c)return d.event.trigger(a,b,c,!0)}});v.focusin||d.each({focus:"focusin",
blur:"focusout"},function(a,b){var c=function(a){d.event.simulate(b,a.target,d.event.fix(a))};d.event.special[b]={setup:function(){var d=this.ownerDocument||this.document||this,f=x.access(d,b);f||d.addEventListener(a,c,!0);x.access(d,b,(f||0)+1)},teardown:function(){var d=this.ownerDocument||this.document||this,f=x.access(d,b)-1;f?x.access(d,b,f):(d.removeEventListener(a,c,!0),x.remove(d,b))}}});var Ca=p.location,Nb=Date.now(),$a=/\?/;d.parseXML=function(a){var b,c;if(!a||"string"!==typeof a)return null;
try{b=(new p.DOMParser).parseFromString(a,"text/xml")}catch(e){}c=b&&b.getElementsByTagName("parsererror")[0];b&&!c||d.error("Invalid XML: "+(c?d.map(c.childNodes,function(a){return a.textContent}).join("\n"):a));return b};var gc=/\[\]$/,Ob=/\r?\n/g,xc=/^(?:submit|button|image|reset|file)$/i,yc=/^(?:input|select|textarea|keygen)/i;d.param=function(a,b){var c,e=[],f=function(a,b){var c=r(b)?b():b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(null==c?"":c)};if(null==a)return"";if(Array.isArray(a)||
a.jquery&&!d.isPlainObject(a))d.each(a,function(){f(this.name,this.value)});else for(c in a)Va(c,a[c],b,f);return e.join("&")};d.fn.extend({serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=d.prop(this,"elements");return a?d.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!d(this).is(":disabled")&&yc.test(this.nodeName)&&!xc.test(a)&&(this.checked||!Ba.test(a))}).map(function(a,b){var c=d(this).val();return null==
c?null:Array.isArray(c)?d.map(c,function(a){return{name:b.name,value:a.replace(Ob,"\r\n")}}):{name:b.name,value:c.replace(Ob,"\r\n")}}).get()}});var zc=/%20/g,Ac=/#.*$/,Bc=/([?&])_=[^&]*/,Cc=/^(.*?):[ \t]*([^\r\n]*)$/mg,Dc=/^(?:GET|HEAD)$/,Ec=/^\/\//,Pb={},Wa={},Qb="*/".concat("*"),ab=u.createElement("a");ab.href=Ca.href;d.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:Ca.href,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(Ca.protocol),global:!0,processData:!0,
async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":Qb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/\bxml\b/,html:/\bhtml/,json:/\bjson\b/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":JSON.parse,"text xml":d.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Xa(Xa(a,d.ajaxSettings),
b):Xa(d.ajaxSettings,a)},ajaxPrefilter:xb(Pb),ajaxTransport:xb(Wa),ajax:function(a,b){function c(a,b,c,h){var l,r,y,u=b;if(!n){n=!0;k&&p.clearTimeout(k);e=void 0;g=h||"";w.readyState=0<a?4:0;h=200<=a&&300>a||304===a;c&&(y=hc(m,w,c));!h&&-1<d.inArray("script",m.dataTypes)&&0>d.inArray("json",m.dataTypes)&&(m.converters["text script"]=function(){});y=ic(m,y,w,h);if(h)m.ifModified&&((c=w.getResponseHeader("Last-Modified"))&&(d.lastModified[f]=c),(c=w.getResponseHeader("etag"))&&(d.etag[f]=c)),204===
a||"HEAD"===m.type?u="nocontent":304===a?u="notmodified":(u=y.state,l=y.data,r=y.error,h=!r);else if(r=u,a||!u)u="error",0>a&&(a=0);w.status=a;w.statusText=(b||u)+"";h?A.resolveWith(v,[l,u,w]):A.rejectWith(v,[w,u,r]);w.statusCode(C);C=void 0;q&&x.trigger(h?"ajaxSuccess":"ajaxError",[w,m,h?l:r]);E.fireWith(v,[w,u]);q&&(x.trigger("ajaxComplete",[w,m]),--d.active||d.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=void 0);b=b||{};var e,f,g,h,k,l,n,q,r,m=d.ajaxSetup({},b),v=m.context||m,x=m.context&&
(v.nodeType||v.jquery)?d(v):d.event,A=d.Deferred(),E=d.Callbacks("once memory"),C=m.statusCode||{},F={},G={},H="canceled",w={readyState:0,getResponseHeader:function(a){var b;if(n){if(!h)for(h={};b=Cc.exec(g);)h[b[1].toLowerCase()+" "]=(h[b[1].toLowerCase()+" "]||[]).concat(b[2]);b=h[a.toLowerCase()+" "]}return null==b?null:b.join(", ")},getAllResponseHeaders:function(){return n?g:null},setRequestHeader:function(a,b){null==n&&(a=G[a.toLowerCase()]=G[a.toLowerCase()]||a,F[a]=b);return this},overrideMimeType:function(a){null==
n&&(m.mimeType=a);return this},statusCode:function(a){var b;if(a)if(n)w.always(a[w.status]);else for(b in a)C[b]=[C[b],a[b]];return this},abort:function(a){a=a||H;e&&e.abort(a);c(0,a);return this}};A.promise(w);m.url=((a||m.url||Ca.href)+"").replace(Ec,Ca.protocol+"//");m.type=b.method||b.type||m.method||m.type;m.dataTypes=(m.dataType||"*").toLowerCase().match(R)||[""];if(null==m.crossDomain){l=u.createElement("a");try{l.href=m.url,l.href=l.href,m.crossDomain=ab.protocol+"//"+ab.host!==l.protocol+
"//"+l.host}catch(y){m.crossDomain=!0}}m.data&&m.processData&&"string"!==typeof m.data&&(m.data=d.param(m.data,m.traditional));yb(Pb,m,b,w);if(n)return w;(q=d.event&&m.global)&&0===d.active++&&d.event.trigger("ajaxStart");m.type=m.type.toUpperCase();m.hasContent=!Dc.test(m.type);f=m.url.replace(Ac,"");m.hasContent?m.data&&m.processData&&0===(m.contentType||"").indexOf("application/x-www-form-urlencoded")&&(m.data=m.data.replace(zc,"+")):(l=m.url.slice(f.length),m.data&&(m.processData||"string"===
typeof m.data)&&(f+=($a.test(f)?"&":"?")+m.data,delete m.data),!1===m.cache&&(f=f.replace(Bc,"$1"),l=($a.test(f)?"&":"?")+"_="+Nb++ +l),m.url=f+l);m.ifModified&&(d.lastModified[f]&&w.setRequestHeader("If-Modified-Since",d.lastModified[f]),d.etag[f]&&w.setRequestHeader("If-None-Match",d.etag[f]));(m.data&&m.hasContent&&!1!==m.contentType||b.contentType)&&w.setRequestHeader("Content-Type",m.contentType);w.setRequestHeader("Accept",m.dataTypes[0]&&m.accepts[m.dataTypes[0]]?m.accepts[m.dataTypes[0]]+
("*"!==m.dataTypes[0]?", "+Qb+"; q=0.01":""):m.accepts["*"]);for(r in m.headers)w.setRequestHeader(r,m.headers[r]);if(m.beforeSend&&(!1===m.beforeSend.call(v,w,m)||n))return w.abort();H="abort";E.add(m.complete);w.done(m.success);w.fail(m.error);if(e=yb(Wa,m,b,w)){w.readyState=1;q&&x.trigger("ajaxSend",[w,m]);if(n)return w;m.async&&0<m.timeout&&(k=p.setTimeout(function(){w.abort("timeout")},m.timeout));try{n=!1,e.send(F,c)}catch(y){if(n)throw y;c(-1,y)}}else c(-1,"No Transport");return w},getJSON:function(a,
b,c){return d.get(a,b,c,"json")},getScript:function(a,b){return d.get(a,void 0,b,"script")}});d.each(["get","post"],function(a,b){d[b]=function(a,e,f,g){r(e)&&(g=g||f,f=e,e=void 0);return d.ajax(d.extend({url:a,type:b,dataType:g,data:e,success:f},d.isPlainObject(a)&&a))}});d.ajaxPrefilter(function(a){for(var b in a.headers)"content-type"===b.toLowerCase()&&(a.contentType=a.headers[b]||"")});d._evalUrl=function(a,b,c){return d.ajax({url:a,type:"GET",dataType:"script",cache:!0,async:!1,global:!1,converters:{"text script":function(){}},
dataFilter:function(a){d.globalEval(a,b,c)}})};d.fn.extend({wrapAll:function(a){this[0]&&(r(a)&&(a=a.call(this[0])),a=d(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&a.insertBefore(this[0]),a.map(function(){for(var a=this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this));return this},wrapInner:function(a){return r(a)?this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?c.wrapAll(a):b.append(a)})},wrap:function(a){var b=
r(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,c):a)})},unwrap:function(a){this.parent(a).not("body").each(function(){d(this).replaceWith(this.childNodes)});return this}});d.expr.pseudos.hidden=function(a){return!d.expr.pseudos.visible(a)};d.expr.pseudos.visible=function(a){return!!(a.offsetWidth||a.offsetHeight||a.getClientRects().length)};d.ajaxSettings.xhr=function(){try{return new p.XMLHttpRequest}catch(a){}};var Fc={0:200,1223:204},ja=d.ajaxSettings.xhr();v.cors=!!ja&&"withCredentials"in
ja;v.ajax=ja=!!ja;d.ajaxTransport(function(a){var b,c;if(v.cors||ja&&!a.crossDomain)return{send:function(d,f){var e,h=a.xhr();h.open(a.type,a.url,a.async,a.username,a.password);if(a.xhrFields)for(e in a.xhrFields)h[e]=a.xhrFields[e];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");for(e in d)h.setRequestHeader(e,d[e]);b=function(a){return function(){b&&(b=c=h.onload=h.onerror=h.onabort=h.ontimeout=h.onreadystatechange=
null,"abort"===a?h.abort():"error"===a?"number"!==typeof h.status?f(0,"error"):f(h.status,h.statusText):f(Fc[h.status]||h.status,h.statusText,"text"!==(h.responseType||"text")||"string"!==typeof h.responseText?{binary:h.response}:{text:h.responseText},h.getAllResponseHeaders()))}};h.onload=b();c=h.onerror=h.ontimeout=b("error");void 0!==h.onabort?h.onabort=c:h.onreadystatechange=function(){4===h.readyState&&p.setTimeout(function(){b&&c()})};b=b("abort");try{h.send(a.hasContent&&a.data||null)}catch(k){if(b)throw k;
}},abort:function(){b&&b()}}});d.ajaxPrefilter(function(a){a.crossDomain&&(a.contents.script=!1)});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/\b(?:java|ecma)script\b/},converters:{"text script":function(a){d.globalEval(a);return a}}});d.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET")});d.ajaxTransport("script",function(a){if(a.crossDomain||a.scriptAttrs){var b,
c;return{send:function(e,f){b=d("<script>").attr(a.scriptAttrs||{}).prop({charset:a.scriptCharset,src:a.url}).on("load error",c=function(a){b.remove();c=null;a&&f("error"===a.type?404:200,a.type)});u.head.appendChild(b[0])},abort:function(){c&&c()}}}});var Rb=[],bb=/(=)\?(?=&|$)|\?\?/;d.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=Rb.pop()||d.expando+"_"+Nb++;this[a]=!0;return a}});d.ajaxPrefilter("json jsonp",function(a,b,c){var e,f,g,h=!1!==a.jsonp&&(bb.test(a.url)?"url":"string"===
typeof a.data&&0===(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&bb.test(a.data)&&"data");if(h||"jsonp"===a.dataTypes[0])return e=a.jsonpCallback=r(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,h?a[h]=a[h].replace(bb,"$1"+e):!1!==a.jsonp&&(a.url+=($a.test(a.url)?"&":"?")+a.jsonp+"="+e),a.converters["script json"]=function(){g||d.error(e+" was not called");return g[0]},a.dataTypes[0]="json",f=p[e],p[e]=function(){g=arguments},c.always(function(){void 0===f?d(p).removeProp(e):
p[e]=f;a[e]&&(a.jsonpCallback=b.jsonpCallback,Rb.push(e));g&&r(f)&&f(g[0]);g=f=void 0}),"script"});v.createHTMLDocument=function(){var a=u.implementation.createHTMLDocument("").body;a.innerHTML="<form></form><form></form>";return 2===a.childNodes.length}();d.parseHTML=function(a,b,c){if("string"!==typeof a)return[];"boolean"===typeof b&&(c=b,b=!1);var e;b||(v.createHTMLDocument?(b=u.implementation.createHTMLDocument(""),e=b.createElement("base"),e.href=u.location.href,b.head.appendChild(e)):b=u);
e=Db.exec(a);c=!c&&[];if(e)return[b.createElement(e[1])];e=ib([a],b,c);c&&c.length&&d(c).remove();return d.merge([],e.childNodes)};d.fn.load=function(a,b,c){var e,f,g,h=this,k=a.indexOf(" ");-1<k&&(e=da(a.slice(k)),a=a.slice(0,k));r(b)?(c=b,b=void 0):b&&"object"===typeof b&&(f="POST");0<h.length&&d.ajax({url:a,type:f||"GET",dataType:"html",data:b}).done(function(a){g=arguments;h.html(e?d("<div>").append(d.parseHTML(a)).find(e):a)}).always(c&&function(a,b){h.each(function(){c.apply(this,g||[a.responseText,
b,a])})});return this};d.expr.pseudos.animated=function(a){return d.grep(d.timers,function(b){return a===b.elem}).length};d.offset={setOffset:function(a,b,c){var e,f,g,h=d.css(a,"position"),k=d(a),l={};"static"===h&&(a.style.position="relative");g=k.offset();f=d.css(a,"top");e=d.css(a,"left");("absolute"===h||"fixed"===h)&&-1<(f+e).indexOf("auto")?(e=k.position(),f=e.top,e=e.left):(f=parseFloat(f)||0,e=parseFloat(e)||0);r(b)&&(b=b.call(a,c,d.extend({},g)));null!=b.top&&(l.top=b.top-g.top+f);null!=
b.left&&(l.left=b.left-g.left+e);"using"in b?b.using.call(a,l):k.css(l)}};d.fn.extend({offset:function(a){if(arguments.length)return void 0===a?this:this.each(function(b){d.offset.setOffset(this,a,b)});var b,c;if(c=this[0]){if(!c.getClientRects().length)return{top:0,left:0};b=c.getBoundingClientRect();c=c.ownerDocument.defaultView;return{top:b.top+c.pageYOffset,left:b.left+c.pageXOffset}}},position:function(){if(this[0]){var a,b,c,e=this[0],f={top:0,left:0};if("fixed"===d.css(e,"position"))b=e.getBoundingClientRect();
else{b=this.offset();c=e.ownerDocument;for(a=e.offsetParent||c.documentElement;a&&(a===c.body||a===c.documentElement)&&"static"===d.css(a,"position");)a=a.parentNode;a&&a!==e&&1===a.nodeType&&(f=d(a).offset(),f.top+=d.css(a,"borderTopWidth",!0),f.left+=d.css(a,"borderLeftWidth",!0))}return{top:b.top-f.top-d.css(e,"marginTop",!0),left:b.left-f.left-d.css(e,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent;a&&"static"===d.css(a,"position");)a=a.offsetParent;
return a||ia})}});d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c="pageYOffset"===b;d.fn[a]=function(d){return V(this,function(a,d,e){var f;ka(a)?f=a:9===a.nodeType&&(f=a.defaultView);if(void 0===e)return f?f[b]:a[d];f?f.scrollTo(c?f.pageXOffset:e,c?e:f.pageYOffset):a[d]=e},a,d,arguments.length)}});d.each(["top","left"],function(a,b){d.cssHooks[b]=pb(v.pixelPosition,function(a,e){if(e)return e=xa(a,b),Qa.test(e)?d(a).position()[b]+"px":e})});d.each({Height:"height",Width:"width"},
function(a,b){d.each({padding:"inner"+a,content:b,"":"outer"+a},function(c,e){d.fn[e]=function(f,g){var h=arguments.length&&(c||"boolean"!==typeof f),k=c||(!0===f||!0===g?"margin":"border");return V(this,function(b,c,f){return ka(b)?0===e.indexOf("outer")?b["inner"+a]:b.document.documentElement["client"+a]:9===b.nodeType?(c=b.documentElement,Math.max(b.body["scroll"+a],c["scroll"+a],b.body["offset"+a],c["offset"+a],c["client"+a])):void 0===f?d.css(b,c,k):d.style(b,c,f,k)},b,h?f:void 0,h)}})});d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),
function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.fn.extend({bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,d){return this.on(b,a,c,d)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});d.each("blur focus focusin focusout resize scroll click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup contextmenu".split(" "),
function(a,b){d.fn[b]=function(a,d){return 0<arguments.length?this.on(b,null,a,d):this.trigger(b)}});var Gc=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;d.proxy=function(a,b){var c,e;"string"===typeof b&&(c=a[b],b=a,a=c);if(r(a))return e=X.call(arguments,2),c=function(){return a.apply(b||this,e.concat(X.call(arguments)))},c.guid=a.guid=a.guid||d.guid++,c};d.holdReady=function(a){a?d.readyWait++:d.ready(!0)};d.isArray=Array.isArray;d.parseJSON=JSON.parse;d.nodeName=E;d.isFunction=r;d.isWindow=ka;d.camelCase=
Q;d.type=H;d.now=Date.now;d.isNumeric=function(a){var b=d.type(a);return("number"===b||"string"===b)&&!isNaN(a-parseFloat(a))};d.trim=function(a){return null==a?"":(a+"").replace(Gc,"")};"function"===typeof define&&define.amd&&define("jquery",[],function(){return d});var Hc=p.jQuery,Ic=p.$;d.noConflict=function(a){p.$===d&&(p.$=Ic);a&&p.jQuery===d&&(p.jQuery=Hc);return d};"undefined"===typeof A&&(p.jQuery=p.$=d);return d});
