/*
 @overview RSVP - a tiny implementation of Promises/A+.
 @copyright Copyright (c) 2016 Yehuda Katz, Tom Dale, Stefan Penner and contributors
 @license   Licensed under MIT license
            See https://raw.githubusercontent.com/tildeio/rsvp.js/master/LICENSE
 @version   4.8.4+ff10049b
*/
var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,g,l){if(l.get||l.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[g]=l.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var g=0;return $jscomp.iteratorPrototype(function(){return g<c.length?{done:!1,value:c[g++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(c,g){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var l=0,p={next:function(){if(l<c.length){var q=l++;return{value:g(q,c[q]),done:!1}}p.next=function(){return{done:!0,value:void 0}};return p.next()}};p[Symbol.iterator]=function(){return p};return p};
$jscomp.polyfill=function(c,g,l,p){if(g){l=$jscomp.global;c=c.split(".");for(p=0;p<c.length-1;p++){var q=c[p];q in l||(l[q]={});l=l[q]}c=c[c.length-1];p=l[c];g=g(p);g!=p&&null!=g&&$jscomp.defineProperty(l,c,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6-impl","es3");
(function(c,g){"object"===typeof exports&&"undefined"!==typeof module?g(exports):"function"===typeof define&&define.amd?define(["exports"],g):g(c.RSVP={})})(this,function(c){function g(a){var b=a._promiseCallbacks;b||(b=a._promiseCallbacks={});return b}function l(a,b){if(2===arguments.length)h[a]=b;else return h[a]}function p(){setTimeout(function(){for(var a=0;a<F.length;a++){var b=F[a],d=b.payload;d.guid=d.key+d.id;d.childGuid=d.key+d.childId;d.error&&(d.stack=d.error.stack);h.trigger(b.name,b.payload)}F.length=
0},50)}function q(a,b,d){1===F.push({name:a,payload:{key:b._guidKey,id:b._id,eventName:a,detail:b._result,childId:d&&d._id,label:b._label,timeStamp:Date.now(),error:h["instrument-with-stack"]?Error(b._label):null}})&&p()}function G(a,b){if(a&&"object"===typeof a&&a.constructor===this)return a;var d=new this(u,b);t(d,a);return d}function u(){}function K(a){try{return a.then}catch(b){return m.error=b,m}}function ra(){try{var a=L;L=null;return a.apply(this,arguments)}catch(b){return m.error=b,m}}function D(a){L=
a;return ra}function sa(a,b,d){h.async(function(a){var f=!1,c=D(d).call(b,function(d){f||(f=!0,b===d?v(a,d):t(a,d))},function(b){f||(f=!0,n(a,b))},"Settle: "+(a._label||" unknown promise"));f||c!==m||(f=!0,c=m.error,m.error=null,n(a,c))},a)}function ta(a,b){b._state===r?v(a,b._result):b._state===w?(b._onError=null,n(a,b._result)):H(b,void 0,function(d){b===d?v(a,d):t(a,d)},function(b){return n(a,b)})}function U(a,b,d){b.constructor===a.constructor&&d===M&&a.constructor.resolve===G?ta(a,b):d===m?(b=
m.error,m.error=null,n(a,b)):"function"===typeof d?sa(a,b,d):v(a,b)}function t(a,b){if(a===b)v(a,b);else{var d=typeof b;null===b||"object"!==d&&"function"!==d?v(a,b):U(a,b,K(b))}}function ua(a){a._onError&&a._onError(a._result);N(a)}function v(a,b){a._state===x&&(a._result=b,a._state=r,0===a._subscribers.length?h.instrument&&q("fulfilled",a):h.async(N,a))}function n(a,b){a._state===x&&(a._state=w,a._result=b,h.async(ua,a))}function H(a,b,d,f){var k=a._subscribers,c=k.length;a._onError=null;k[c]=b;
k[c+r]=d;k[c+w]=f;0===c&&a._state&&h.async(N,a)}function N(a){var b=a._subscribers,d=a._state;h.instrument&&q(d===r?"fulfilled":"rejected",a);if(0!==b.length){for(var f,k,c=a._result,e=0;e<b.length;e+=3)f=b[e],k=b[e+d],f?V(d,f,k,c):k(c);a._subscribers.length=0}}function V(a,b,d,f){var k="function"===typeof d;d=k?D(d)(f):f;b._state===x&&(d===b?n(b,new TypeError("A promises callback cannot return that same promise.")):d===m?(a=m.error,m.error=null,n(b,a)):k?t(b,d):a===r?v(b,d):a===w&&n(b,d))}function va(a,
b){var d=!1;try{b(function(b){d||(d=!0,t(a,b))},function(b){d||(d=!0,n(a,b))})}catch(f){n(a,f)}}function M(a,b,d){var f=this._state;if(f===r&&!a||f===w&&!b)return h.instrument&&q("chained",this,this),this;this._onError=null;var k=new this.constructor(u,d),c=this._result;h.instrument&&q("chained",this,k);if(f===x)H(this,k,a,b);else{var e=f===r?a:b;h.async(function(){return V(f,k,e,c)})}return k}function W(a,b,d){this._remaining--;this._result[b]=a===r?{state:"fulfilled",value:d}:{state:"rejected",
reason:d}}function wa(a,b){return{then:function(d,f){return a.call(b,d,f)}}}function X(a,b){var d=function(){for(var d=arguments.length,c=Array(d+1),z=!1,h=0;h<d;++h){var g=arguments[h];if(!z){z=null!==g&&"object"===typeof g?g.constructor===e?!0:K(g):!1;if(z===m)return d=m.error,m.error=null,c=new e(u),n(c,d),c;z&&!0!==z&&(g=wa(z,g))}c[h]=g}var l=new e(u);c[d]=function(a,d){if(a)n(l,a);else if(void 0===b)t(l,d);else if(!0===b){for(var f=arguments,c=f.length,k=Array(c-1),e=1;e<c;e++)k[e-1]=f[e];t(l,
k)}else if(Array.isArray(b)){for(var k=arguments,f={},e=k.length,c=Array(e),g=0;g<e;g++)c[g]=k[g];for(k=0;k<b.length;k++)f[b[k]]=c[k+1];t(l,f)}else t(l,d)};return z?xa(l,c,a,this):Y(l,c,a,this)};d.__proto__=a;return d}function Y(a,b,d,f){D(d).apply(f,b)===m&&(b=m.error,m.error=null,n(a,b));return a}function xa(a,b,d,f){return e.all(b).then(function(b){return Y(a,b,d,f)})}function Z(a,b){return e.all(a,b)}function ya(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+
typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}function aa(a,b){return Array.isArray(a)?(new ba(e,a,b)).promise:e.reject(new TypeError("Promise.allSettled must be called with an array"),b)}function ca(a,b){return e.race(a,b)}function za(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);
a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}function da(a,b){return e.resolve(a,b).then(function(a){if(null===a||"object"!==typeof a)throw new TypeError("Promise.hash must be called with an object");return(new ea(e,a,b)).promise})}function Aa(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);
a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}function fa(a,b){return e.resolve(a,b).then(function(a){if(null===a||"object"!==typeof a)throw new TypeError("hashSettled must be called with an object");return(new ga(e,a,!1,b)).promise})}function ha(a){setTimeout(function(){throw a;});throw a;}function ia(a){var b={resolve:void 0,reject:void 0};b.promise=new e(function(a,
f){b.resolve=a;b.reject=f},a);return b}function Ba(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}function ja(a,b,d){return"function"!==typeof b?e.reject(new TypeError("map expects a function as a second argument"),d):e.resolve(a,d).then(function(a){if(!Array.isArray(a))throw new TypeError("map must be called with an array");
return(new ka(e,a,b,d)).promise})}function I(a,b){return e.resolve(a,b)}function la(a,b){return e.reject(a,b)}function Ca(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}function ma(a,b,d){return"function"!==typeof b?e.reject(new TypeError("filter expects function as a second argument"),
d):e.resolve(a,d).then(function(a){if(!Array.isArray(a))throw new TypeError("filter must be called with an array");return(new Da(e,a,b,d)).promise})}function O(a,b){A[B]=a;A[B+1]=b;B+=2;2===B&&na()}function Ea(){var a=process.nextTick,b=process.versions.node.match(/^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/);Array.isArray(b)&&"0"===b[1]&&"10"===b[2]&&(a=setImmediate);return function(){return a(E)}}function Fa(){return"undefined"!==typeof P?function(){P(E)}:Q()}function Ga(){var a=0,b=new oa(E),d=document.createTextNode("");
b.observe(d,{characterData:!0});return function(){return d.data=a=++a%2}}function Ha(){var a=new MessageChannel;a.port1.onmessage=E;return function(){return a.port2.postMessage(0)}}function Q(){return function(){return setTimeout(E,1)}}function E(){for(var a=0;a<B;a+=2)(0,A[a])(A[a+1]),A[a]=void 0,A[a+1]=void 0;B=0}function Ia(){try{var a=Function("return this")().require("vertx");P=a.runOnLoop||a.runOnContext;return Fa()}catch(b){return Q()}}function R(){h.on.apply(h,arguments)}function pa(){h.off.apply(h,
arguments)}var S={mixin:function(a){a.on=this.on;a.off=this.off;a.trigger=this.trigger;a._promiseCallbacks=void 0;return a},on:function(a,b){if("function"!==typeof b)throw new TypeError("Callback must be a function");var d=g(this),f=d[a];f||(f=d[a]=[]);-1===f.indexOf(b)&&f.push(b)},off:function(a,b){var d=g(this);if(b){var d=d[a],f=d.indexOf(b);-1!==f&&d.splice(f,1)}else d[a]=[]},trigger:function(a,b,d){if(a=g(this)[a])for(var f,c=0;c<a.length;c++)f=a[c],f(b,d)}},h={instrument:!1};S.mixin(h);var F=
[],x=void 0,r=1,w=2,m={error:null},L=void 0,J=function(){function a(b,a,f,c){this._instanceConstructor=b;this.promise=new b(u,c);this._abortOnReject=f;this._isUsingOwnPromise=b===e;this._isUsingOwnResolve=b.resolve===G;this._init.apply(this,arguments)}a.prototype._init=function(b,a){var d=a.length||0;this._remaining=this.length=d;this._result=Array(d);this._enumerate(a)};a.prototype._enumerate=function(b){for(var a=this.length,f=this.promise,c=0;f._state===x&&c<a;c++)this._eachEntry(b[c],c,!0);this._checkFullfillment()};
a.prototype._checkFullfillment=function(){0===this._remaining&&(v(this.promise,this._result),this._result=null)};a.prototype._settleMaybeThenable=function(b,a,c){var d=this._instanceConstructor;if(this._isUsingOwnResolve){var f=K(b);f===M&&b._state!==x?(b._onError=null,this._settledAt(b._state,a,b._result,c)):"function"!==typeof f?this._settledAt(r,a,b,c):this._isUsingOwnPromise?(d=new d(u),U(d,b,f),this._willSettleAt(d,a,c)):this._willSettleAt(new d(function(a){return a(b)}),a,c)}else this._willSettleAt(d.resolve(b),
a,c)};a.prototype._eachEntry=function(a,d,c){null!==a&&"object"===typeof a?this._settleMaybeThenable(a,d,c):this._setResultAt(r,d,a,c)};a.prototype._settledAt=function(a,d,c,k){var b=this.promise;b._state===x&&(this._abortOnReject&&a===w?n(b,c):(this._setResultAt(a,d,c,k),this._checkFullfillment()))};a.prototype._setResultAt=function(a,d,c,k){this._remaining--;this._result[d]=c};a.prototype._willSettleAt=function(a,d,c){var b=this;H(a,void 0,function(a){return b._settledAt(r,d,a,c)},function(a){return b._settledAt(w,
d,a,c)})};return a}(),C="rsvp_"+Date.now()+"-",Ja=0,e=function(){function a(b,d){this._id=Ja++;this._label=d;this._result=this._state=void 0;this._subscribers=[];h.instrument&&q("created",this);if(u!==b){if("function"!==typeof b)throw new TypeError("You must pass a resolver function as the first argument to the promise constructor");if(this instanceof a)va(this,b);else throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");
}}a.prototype._onError=function(a){var b=this;h.after(function(){b._onError&&h.trigger("error",a,b._label)})};a.prototype["catch"]=function(a,d){return this.then(void 0,a,d)};a.prototype["finally"]=function(a,d){var b=this.constructor;return"function"===typeof a?this.then(function(d){return b.resolve(a()).then(function(){return d})},function(d){return b.resolve(a()).then(function(){throw d;})}):this.then(a,a)};return a}();e.cast=G;e.all=function(a,b){return Array.isArray(a)?(new J(this,a,!0,b)).promise:
this.reject(new TypeError("Promise.all must be called with an array"),b)};e.race=function(a,b){var d=new this(u,b);if(!Array.isArray(a))return n(d,new TypeError("Promise.race must be called with an array")),d;for(var c=0;d._state===x&&c<a.length;c++)H(this.resolve(a[c]),void 0,function(a){return t(d,a)},function(a){return n(d,a)});return d};e.resolve=G;e.reject=function(a,b){var d=new this(u,b);n(d,a);return d};e.prototype._guidKey=C;e.prototype.then=M;var ba=function(a){function b(b,c,k){b=a.call(this,
b,c,!1,k);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!b||"object"!==typeof b&&"function"!==typeof b?this:b}ya(b,a);return b}(J);ba.prototype._setResultAt=W;var ea=function(a){function b(b,c){var d=a.call(this,b,c,2<arguments.length&&void 0!==arguments[2]?arguments[2]:!0,arguments[3]);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!d||"object"!==typeof d&&"function"!==typeof d?this:d}za(b,
a);b.prototype._init=function(a,b){this._result={};this._enumerate(b)};b.prototype._enumerate=function(a){var b=Object.keys(a),d=b.length,c=this.promise;this._remaining=d;for(var e,g,h=0;c._state===x&&h<d;h++)e=b[h],g=a[e],this._eachEntry(g,e,!0);this._checkFullfillment()};return b}(J),ga=function(a){function b(b,c,e){b=a.call(this,b,c,!1,e);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!b||"object"!==typeof b&&"function"!==typeof b?this:b}Aa(b,
a);return b}(ea);ga.prototype._setResultAt=W;var ka=function(a){function b(b,c,e,g){b=a.call(this,b,c,!0,g,e);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!b||"object"!==typeof b&&"function"!==typeof b?this:b}Ba(b,a);b.prototype._init=function(a,b,c,e,g){this._remaining=this.length=a=b.length||0;this._result=Array(a);this._mapFn=g;this._enumerate(b)};b.prototype._setResultAt=function(a,b,c,e){e?(a=D(this._mapFn)(c,b),a===m?this._settledAt(w,
b,a.error,!1):this._eachEntry(a,b,!1)):(this._remaining--,this._result[b]=c)};return b}(J),qa={},Da=function(a){function b(){var b=a.apply(this,arguments);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!b||"object"!==typeof b&&"function"!==typeof b?this:b}Ca(b,a);b.prototype._checkFullfillment=function(){if(0===this._remaining&&null!==this._result){var a=this._result.filter(function(a){return a!==qa});v(this.promise,a);this._result=null}};b.prototype._setResultAt=
function(a,b,c,e){e?(this._result[b]=c,a=D(this._mapFn)(c,b),a===m?this._settledAt(w,b,a.error,!1):this._eachEntry(a,b,!1)):(this._remaining--,c||(this._result[b]=qa))};return b}(ka),B=0,P=void 0,y=(C="undefined"!==typeof window?window:void 0)||{},oa=y.MutationObserver||y.WebKitMutationObserver,y="undefined"===typeof self&&"undefined"!==typeof process&&"[object process]"==={}.toString.call(process),Ka="undefined"!==typeof Uint8ClampedArray&&"undefined"!==typeof importScripts&&"undefined"!==typeof MessageChannel,
A=Array(1E3),na=void 0,na=y?Ea():oa?Ga():Ka?Ha():void 0===C&&"function"===typeof require?Ia():Q();h.async=O;h.after=function(a){return setTimeout(a,0)};C=function(a,b){return h.async(a,b)};if("undefined"!==typeof window&&"object"===typeof window.__PROMISE_INSTRUMENTATION__){y=window.__PROMISE_INSTRUMENTATION__;l("instrument",!0);for(var T in y)y.hasOwnProperty(T)&&R(T,y[T])}c["default"]={asap:O,cast:I,Promise:e,EventTarget:S,all:Z,allSettled:aa,race:ca,hash:da,hashSettled:fa,rethrow:ha,defer:ia,denodeify:X,
configure:l,on:R,off:pa,resolve:I,reject:la,map:ja,async:C,filter:ma};c.asap=O;c.cast=I;c.Promise=e;c.EventTarget=S;c.all=Z;c.allSettled=aa;c.race=ca;c.hash=da;c.hashSettled=fa;c.rethrow=ha;c.defer=ia;c.denodeify=X;c.configure=l;c.on=R;c.off=pa;c.resolve=I;c.reject=la;c.map=ja;c.async=C;c.filter=ma;Object.defineProperty(c,"__esModule",{value:!0})});
