var abp=function(){function p(a,c){for(;a.length<c;)a="0"+a;return a}function t(b,c,e,d,f){var g=a.getTypeBitSize(e),h=b.bitoffset+g,m=4*c.length;b.value=null;m>=h&&(a.isPadType(e)?b.value=0:a.isBitType(e)||e==a.BOOL1?(b.value=8<h?l(c,a.UINT16,1):l(c,a.UINT8,d),null!=b.value&&(b.value>>=b.bitoffset,b.value&=(1<<g)-1,b.value=e==a.BOOL1?0==b.value?!1:!0:"0x"+b.value.toString(16).toUpperCase())):b.value=a.parseValue(c,e,d,f));b.bitoffset+=g;8<=b.bitoffset&&(b.byteoffset+=Math.floor(b.bitoffset/8),b.bitoffset%=
8);return b}function l(b,c,e){b=parseInt(b,16);if(e)switch(c){case a.UINT16:case a.SINT16:b=endianess.swap16(b)>>>0;break;case a.UINT32:case a.SINT32:b=endianess.swap32(b)>>>0}if(c==a.SINT32||c==a.SINT16||c==a.SINT8)c=1<<8*a.getTypeSize(c)-1>>>0,b&c&&(b-=2*c);return b}function u(b,c,e){b=parseInt(b,16);if(e)switch(c){case a.BITS16:b=endianess.swap16(b)>>>0;break;case a.BITS32:b=endianess.swap32(b)>>>0}return"0x"+("00000000"+b.toString(16).toUpperCase()).substr(-2*a.getTypeSize(c))}function v(b,c,
e,d){var f=a.getTypeBitSize(e);if(a.isTypeWithBitAlignment(e))for(b.buffer|=c<<b.bitoffset,b.bitoffset+=f;8<=b.bitoffset;)b.hex+=a.encodeValue(b.buffer&255,abp.UINT8,d),b.buffer>>=8,b.bitoffset-=8;else 0<b.bitoffset&&(b.hex+=a.encodeValue(b.buffer&255,abp.UINT8,d),b.buffer=0,b.bitoffset=0),b.hex+=a.encodeValue(c,e,d);return b}function x(a,c){if(a!=a){var b=2143289344;c&&(b=endianess.swap32(b));return(b+4294967296).toString(16).substr(-8).toLowerCase()}var b=0>a||0==a&&0>1/a?2147483648:0,d=Math.abs(a);
if(d==Number.POSITIVE_INFINITY)return b|=2139095040,c&&(b=endianess.swap32(b)),(b+4294967296).toString(16).substr(-8).toLowerCase();for(var f=0;2<=d&&f<=k;)f++,d/=2;for(;1>d&&f>=-(k-1);)f--,d*=2;f+=k;if(255==f)return b|2139095040;d=0==f?d*Math.pow(2,23)/2:d*Math.pow(2,23)-Math.pow(2,23);d=d.toFixed();b=b|f<<23&2139095040|d&8388607;c&&(b=endianess.swap32(b));return(b+4294967296).toString(16).substr(-8).toLowerCase()}function n(b,c,e){var d=a.getTypeSize(c);if("string"==typeof b||b>a.getTypeMax(c)||
b<a.getTypeMin(c))return null;c==a.SINT32?0>b&&(b>>>=0):(c==a.SINT16||c==a.SINT8)&&0>b&&(b+=1<<8*d);if(e)switch(c){case a.UINT16:case a.SINT16:case a.BITS16:b=endianess.swap16(b);break;case a.UINT32:case a.SINT32:case a.BITS32:b=endianess.swap32(b)}0>b&&(b>>>=0);b=b.toString(16);return b.length>2*d?null:p(b,2*d)}var q=(new Big(2)).pow(32),y=(new Big(2)).pow(64),w=Number.MAX_VALUE,r=new Big(0),k=Math.pow(2,7)-1,a={BOOL:0,SINT8:1,SINT16:2,SINT32:3,UINT8:4,UINT16:5,UINT32:6,CHAR:7,ENUM:8,BITS8:9,BITS16:10,
BITS32:11,OCTET:12,SINT64:16,UINT64:17,FLOAT:18,DOUBLE:19,PAD0:32,PAD1:33,PAD2:34,PAD3:35,PAD4:36,PAD5:37,PAD6:38,PAD7:39,PAD8:40,PAD9:41,PAD10:42,PAD11:43,PAD12:44,PAD13:45,PAD14:46,PAD15:47,PAD16:48,BOOL1:64,BIT1:65,BIT2:66,BIT3:67,BIT4:68,BIT5:69,BIT6:70,BIT7:71,ERR_NO_ERROR:0,ERR_INV_MSG_FORMAT:2,ERR_UNSUP_OBJ:3,ERR_UNSUP_INST:4,ERR_UNSUP_CMD:5,ERR_INV_CMD_EXT_0:6,ERR_INV_CMD_EXT_1:7,ERR_ATTR_NOT_SETABLE:8,ERR_ATTR_NOT_GETABLE:9,ERR_TOO_MUCH_DATA:10,ERR_NOT_ENOUGH_DATA:11,ERR_OUT_OF_RANGE:12,
ERR_INV_STATE:13,ERR_NO_RESOURCES:14,ERR_SEG_FAILURE:15,ERR_SEG_BUF_OVERFLOW:16,ERR_VAL_TOO_HIGH:17,ERR_VAL_TOO_LOW:18,ERR_CTRL_FROM_OTHER_CHANNEL:19,ERR_MSG_CHANNEL_TOO_SMALL:20,ERR_GENERAL_ERROR:21,ERR_PROTECTED_ACCESS:22,ERR_MALFORMED_RESPONSE:256,ERR_OVERSIZED_RESPONSE:257,ERR_UNDERSIZED_RESPONSE:258,ERR_OBJ_SPECIFIC:255,FORMAT_LE:0,FORMAT_BE:1,parseValue:function(b,c,e,d){var f=a.getTypeSize(c);if(b.length/2!=f)return null;"undefined"===typeof d&&(d=1);switch(c){case a.UINT16:case a.UINT32:case a.SINT16:case a.SINT32:if("undefined"===
typeof e)throw"Cannot parse integers without endianess";case a.UINT8:case a.SINT8:return l(b,c,e);case a.BITS16:case a.BITS32:if("undefined"===typeof e)throw"Cannot parse integers without endianess";case a.BITS8:case a.BIT7:case a.BIT6:case a.BIT5:case a.BIT4:case a.BIT3:case a.BIT2:case a.BIT1:return u(b,c,e);case a.OCTET:return 1==d?u(b,c,e):b.toString(16);case a.SINT64:case a.UINT64:if("undefined"===typeof e)throw"Cannot parse big integers without endianess";e&&(b=endianess.swaphex(b));e=new Big(parseInt(b.substring(0,
8),16));b=new Big(parseInt(b.substring(8,16),16));e=e.times(q).plus(b);null==e?c=null:(c==a.SINT64&&(c=a.getTypeSize(c),c=(new Big(2)).pow(8*c-1),e.div(c).round(0,0).mod(2).eq(r)||(e=e.minus(c.times(2)))),c=e);return c;case a.BOOL:case a.BOOL1:return c=l(b,a.UINT8),null==c?null:0==c?!1:!0;case a.ENUM:return l(b,a.UINT8);case a.CHAR:return String.fromCharCode(l(b,a.UINT8));case a.FLOAT:if("undefined"===typeof e)throw"Cannot parse floats without endianess";a:if(c=parseInt(b,16),e&&(c=endianess.swap32(c)),
e=c&2147483648?-1:1,b=(c>>23&255)-k,c&=8388607,b==k+1)c=e*(c?Number.NaN:Number.POSITIVE_INFINITY);else{if(b==-k){if(0==c){c=0*e;break a}b=-(k-1);c/=8388608}else c=(c|8388608)/8388608;c=e*c*Math.pow(2,b)}return c;case a.DOUBLE:if("undefined"===typeof e)throw"Cannot parse doubles without endianess";return parseIEEEDouble(b,e);default:return null}},parseArray:function(b,c,e,d){var f,g={value:0,byteoffset:0,bitoffset:0},h;"undefined"===typeof d&&(d=1);var m=a.getTypeBitSize(c);if(0==m||null==m)return null;
h=Math.floor(4*b.length/m);f=Array(h);for(var k=0;k<h;k++){var l=b.substr(2*g.byteoffset,2*Math.ceil((g.bitoffset+m)/8)),g=t(g,l,c,e,d);f[k]=g.value}return f},parseStruct:function(b,c,e,d){for(var f=Array(c.length),g={value:0,byteoffset:0,bitoffset:0},h=0;h<c.length;h++){if(a.isTypeWithBitAlignment(c[h])){if(1<d[h])return null}else 0!=g.bitoffset&&(g.byteoffset++,g.bitoffset=0);var k=a.getTypeBitSize(c[h]);f[h]=Array(d[h]);for(var l=0;l<d[h];l++){var n=b.substr(2*g.byteoffset,2*Math.ceil((g.bitoffset+
k)/8)),g=t(g,n,c[h],e,d[h]);f[h][l]=g.value}}return f},encodeValue:function(b,c,e){switch(c){case a.UINT16:case a.UINT32:case a.SINT16:case a.SINT32:case a.BITS16:case a.BITS32:if("undefined"===typeof e)throw"Cannot encode integers without endianess";case a.UINT8:case a.SINT8:case a.BITS8:case a.OCTET:case a.BIT1:case a.BIT2:case a.BIT3:case a.BIT4:case a.BIT5:case a.BIT6:case a.BIT7:return n(b,c,e);case a.UINT64:case a.SINT64:if("undefined"===typeof e)throw"Cannot encode big integers without endianess";
var d=b;b=a.getTypeSize(c);"object"!=typeof d||d.gt(a.getTypeMax(c))||d.lt(a.getTypeMin(c))?e=null:(c==a.SINT64&&d.lt(r)&&(d=d.plus((new Big(2)).pow(8*b))),d.gt(y)?c=null:d.lt(r)?c=null:(c=d.div(q).round(0,0),d=d.minus(c.times(q)),c=parseInt(c.toString(),10).toString(16)+p(parseInt(d.toString(),10).toString(16),8)),null==c?e=null:(c=p(c,2*b),e=e?endianess.swaphex(c):c));return e;case a.BOOL1:case a.BOOL:return n(b?1:0,a.UINT8);case a.ENUM:return n(b,a.UINT8);case a.CHAR:return n(b.charCodeAt(0),a.UINT8);
case a.FLOAT:if("undefined"===typeof e)throw"Cannot encode float without endianess";return x(b,e);case a.DOUBLE:if("undefined"===typeof e)throw"Cannot encode double without endianess";return encodeIEEEDouble(b,e);default:return null}},encodeArray:function(b,c,e){for(var d={hex:"",buffer:0,byteoffset:0,bitoffset:0},f=0;f<b.length;f++)d=v(d,b[f],c,e);0<d.bitoffset&&(d.hex+=a.encodeValue(d.buffer,abp.UINT8,e));return d.hex.toUpperCase()},encodeStruct:function(b,c,e){if(b.constructor!==Array||c.constructor!==
Array)return null;for(var d={hex:"",buffer:0,byteoffset:0,bitoffset:0},f=0;f<c.length;f++)for(var g=0;g<b[f].length;g++)d=v(d,b[f].constructor==Array?b[f][g]:b[f],c[f],e);0<d.bitoffset&&(d.hex+=a.encodeValue(d.buffer,abp.UINT8,e));return d.hex.toUpperCase()},getTypeBitSize:function(b){switch(b){case a.BOOL1:return 1;case a.BIT1:case a.BIT2:case a.BIT3:case a.BIT4:case a.BIT5:case a.BIT6:case a.BIT7:return b-a.BIT1+1;case a.PAD0:case a.PAD1:case a.PAD2:case a.PAD3:case a.PAD4:case a.PAD5:case a.PAD6:case a.PAD7:case a.PAD8:case a.PAD9:case a.PAD10:case a.PAD11:case a.PAD12:case a.PAD13:case a.PAD14:case a.PAD15:case a.PAD16:return b-
a.PAD0;case a.BOOL:case a.ENUM:case a.CHAR:case a.UINT8:case a.SINT8:case a.BITS8:case a.OCTET:return 8;case a.UINT16:case a.SINT16:case a.BITS16:return 16;case a.UINT32:case a.SINT32:case a.BITS32:case a.FLOAT:return 32;case a.UINT64:case a.SINT64:case a.DOUBLE:return 64;default:return null}},getTypeSize:function(b){switch(b){case a.BIT1:case a.BIT2:case a.BIT3:case a.BIT4:case a.BIT5:case a.BIT6:case a.BIT7:case a.BOOL:case a.BOOL1:case a.ENUM:case a.CHAR:case a.UINT8:case a.SINT8:case a.BITS8:case a.OCTET:case a.PAD1:case a.PAD2:case a.PAD3:case a.PAD4:case a.PAD5:case a.PAD6:case a.PAD7:case a.PAD8:return 1;
case a.UINT16:case a.SINT16:case a.BITS16:case a.PAD9:case a.PAD10:case a.PAD11:case a.PAD12:case a.PAD13:case a.PAD14:case a.PAD15:case a.PAD16:return 2;case a.UINT32:case a.SINT32:case a.BITS32:case a.FLOAT:return 4;case a.UINT64:case a.SINT64:case a.DOUBLE:return 8;default:return null}},getTypeMax:function(b){var c=Big(2).pow(8*a.getTypeSize(b));b==a.SINT64?c=c.div(2).sub(1):b==a.UINT64?c=c.sub(1):b==a.SINT32||b==a.SINT16||b==a.SINT8?c=c/2-1:b==a.FLOAT?c=3.402823466E38:b==a.DOUBLE?c=w:b==a.BOOL1?
c=1:a.isBitType(b)?c=(1<<b)-1:a.isPadType(b)?c=0:--c;return b==a.CHAR?String.fromCharCode(c):c},getTypeMin:function(b){var c=Big(2).pow(8*a.getTypeSize(b)-1),c=b==a.SINT64?c.mul(-1):b==a.UINT64?Big(0):b==a.SINT32||b==a.SINT16||b==a.SINT8?-1*c:b==a.FLOAT?-3.402823466E38:b==a.DOUBLE?-w:0;return b==a.CHAR?String.fromCharCode(c):c},errorToString:function(b){switch(b){case a.ERR_NO_ERROR:return"No error";case a.ERR_INV_MSG_FORMAT:return"Invalid message format";case a.ERR_UNSUP_OBJ:return"Unsupported object";
case a.ERR_UNSUP_INST:return"Unsupported instance";case a.ERR_UNSUP_CMD:return"Unsupported command";case a.ERR_INV_CMD_EXT_0:return"Invalid CmdExt[ 0 ]";case a.ERR_INV_CMD_EXT_1:return"Invalid CmdExt[ 1 ]";case a.ERR_ATTR_NOT_SETABLE:return"Attribute access is not set-able";case a.ERR_ATTR_NOT_GETABLE:return"Attribute access is not get-able";case a.ERR_TOO_MUCH_DATA:return"Too much data in msg data field";case a.ERR_NOT_ENOUGH_DATA:return"Not enough data in msg data field";case a.ERR_OUT_OF_RANGE:return"Out of range";
case a.ERR_INV_STATE:return"Invalid state";case a.ERR_NO_RESOURCES:return"Out of resources";case a.ERR_SEG_FAILURE:return"Segmentation failure";case a.ERR_SEG_BUF_OVERFLOW:return"Segmentation buffer overflow";case a.ERR_VAL_TOO_HIGH:return"Written data value is too high";case a.ERR_VAL_TOO_LOW:return"Written data value is too low";case a.ERR_CTRL_FROM_OTHER_CHANNEL:return"Controlled from other channel";case a.ERR_MSG_CHANNEL_TOO_SMALL:return"Message channel too small";case a.ERR_GENERAL_ERROR:return"General error";
case a.ERR_PROTECTED_ACCESS:return"Protected access";case a.ERR_MALFORMED_RESPONSE:return"Malformed response";case a.ERR_OVERSIZED_RESPONSE:return"Too much data in response msg data field";case a.ERR_UNDERSIZED_RESPONSE:return"Not enough data in response msg data field";case a.ERR_OBJ_SPECIFIC:return"Object specific error";default:return"Unknown error"}},isPadType:function(b){return b>=a.PAD0&&b<=a.PAD16},isBitType:function(b){return b>=a.BIT1&&b<=a.BIT7},isTypeWithBitAlignment:function(b){return a.isBitType(b)||
a.isPadType(b)||b==a.BOOL1}};return a}();
