[EIP]
UUTFWFilePath_RECOVERY_HMS = C:\Emerson\SolaHD\SCM-E-EIP\PCBA\EIP_Firmware\WriteProtect_Disable\SCM-E-EIP-HMS.hex
UUTFWFilePath_BL = C:\Emerson\SolaHD\SCM-E-EIP\PCBA\EIP_Firmware\2.01\SCM-E-Bootloader.bin
UUTFWFilePath_BL_Addr = 0x08000000
UUTFWFilePath_HMS = C:\Emerson\SolaHD\SCM-E-EIP\PCBA\EIP_Firmware\2.01\SCM-E-EIP-HMS.bin
UUTFWFilePath_HMS_Addr = 0x08020000
UUTFWFilePath_B40 = C:\Emerson\SolaHD\SCM-E-EIP\PCBA\EIP_Firmware\B40_EIP_FW\ABCC_40_EIP_7351_1_59_02.hiff
SCM_ModelRev = AU
SCM_PriRev = 01
SCM_SecRev = 11 
SDN1_PartNumber = SDN 10-24-100D
SDN2_PartNumber = SDN 10-24-100D
GUI_SourceFile = C:\Emerson\SolaHD\SCM-E-EIP\PCBA\EIP_GUI_Source_File\GUI_2.0.2
CSVFilePath_FRU = C:\Emerson\SolaHD\SCM-E-EIP\PCBA\TesterSpecific\FRU PROGRAMMING TOOLKIT\Data\FRU Array.csv
;ScriptFilePath_EraseFW = C:\Emerson\SolaHD\SCM-E-EIP\PCBA\TesterSpecific\JLink\erase_firmware.bat
;ScriptFilePath_UploadFW = C:\Emerson\SolaHD\SCM-E-EIP\PCBA\TesterSpecific\JLink\upload_firmware.bat
;JFlashFilePath_Project = C:\Emerson\SolaHD\SCM-E-EIP\PCBA\TesterSpecific\J-Link\STM32F722RE.jflash
Webscraper_Timeout = 90